### ISSUE TITLE
SMOKE smoke_coder.py代码bug

### ISSUE THREAD

**Issue by neonhanako** [PaddlePaddle/Paddle3D#104]
此问题在验证阶段中产生（即训练参数中添加了--do_val）

在paddle3d/models/detection/smoke/smoke_coder.py文件中，验证阶段运行到detection_location函数
![image](https://user-images.githubusercontent.com/40436455/192274689-d8cf7340-efb4-481e-8e2d-0e3a4c4b0d56.png)
获取obj_id一行，在超参max_detection无法被val_batch整除的情况下会报错。

实际上，我个人感觉这段代码就有问题。

因为 验证阶段（后处理部分）和 训练阶段（损失计算）都使用了这个函数，然而 训练阶段 函数输入参数中points和points_offset都是batch_size所有的变量，对于训练阶段而言，这段代码没有任何问题。

然而，考虑到 验证阶段 的函数上下文（即smoke.py中smoke 网络forward函数中关于验证的描述），此时这个函数内points和points_offset都是针对单个样本，obj_id应该是为了索引出按batch_size组织的trans_mats和Ks_inv对应的该单个样本的值吧。
然而代码的逻辑，即使在max_detection被val_batch整除的情况下，即不报错的情况下，计算出的obj_id却值意义不明。

可以解决这个Bug，或者讲一讲这里obj_id的意义吗？感谢！

**Comment by nepeplwu** [comment]
@neonhanako 感谢反馈，obj_id的作用确实是为了在batch化的场景下，找到每个样本正确的Ks和trans_mat。目前评估这里的处理问题是已知的（只能处理batch_size为1的场景），之前是为了规避另外一个并行化问题，在评估时强制要求只能输入bs为1，我们会再排查下这里的问题看看是否可以修复。

**Comment by nepeplwu** [comment]
@neonhanako 该问题已经在 [PR107](https://github.com/PaddlePaddle/Paddle3D/pull/107) 中修复，可以先拉取试试看
