### ISSUE TITLE
Try to load the RGB-D image of Rope3D and training SMOKE，but the result is not good as expected. 

### ISSUE THREAD

**Issue by clw5180** [PaddlePaddle/Paddle3D#105]
I try to concat the depth_map with rgb image both in training and testing pipeline for SMOKE, however the AP40 is almost same as rgb input, not as the Rope3D paper said. Is there something tricky? Thanks to big olds !

**Comment by nepeplwu** [comment]
@clw5180 训练配置是否和论文中提到的一致？
