### ISSUE TITLE
smoke onnx 导出问题

### ISSUE THREAD

**Issue by Kerry678231** [PaddlePaddle/Paddle3D#106]
您好，通过以下指令；报以下错误，请问这个要如何解决呢？
Oops, there are some operators not supported yet, including inverse,

paddle2onnx --model_dir exported_model \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file model.onnx \
            --enable_dev_version True

**Comment by nepeplwu** [comment]
@Kerry678231 有更详细的报错信息吗

**Comment by Kerry678231** [comment]
@nepeplwu 我是按照paddle2onnx教程然后转换到你们官方的模型，然后所有到信息如下：
paddle2onnx 中我看其他参数也没有打开更详细到日志，请问以下到日志可以吗？

smoke的模型文件是如下指令获得的：
python tools/export.py --config configs/smoke/smoke_dla34_no_dcn_kitti.yml --model model.pdparams 

paddle2onnx --model_dir exported_model \
  --model_filename inference.pdmodel \
  --params_filename inference.pdiparams \
  --save_file model.onnx \
  --enable_dev_version True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: exported_model/inference.pdmodel
[Paddle2ONNX] Paramters file path: exported_model/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including inverse,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)

**Comment by nepeplwu** [comment]
@Kerry678231 这个是因为onnx不支持 `inverse` 算子导致，可以参考 **[issue60](https://github.com/PaddlePaddle/Paddle3D/issues/60)** 的做法试试看

**Comment by Kerry678231** [comment]
@nepeplwu 收到十分感谢
