### ISSUE TITLE
Error while exporting the PointPillars network

### ISSUE THREAD

**Issue by ZhuoranLyu** [PaddlePaddle/Paddle3D#114]
Hi there, 
I met an error while exporting the PointPillars network using Paddlepaddle.
`python tools/export.py \
    --config configs/pointpillars/pointpillars_xyres16_kitti_car.yml \
    --model /path/to/model.pdparams \
    --save_dir /path/to/output`

And here is the error:
![1666246346(1)](https://user-images.githubusercontent.com/8801452/196869898-836fc0ec-97ba-4827-b040-38cfa32d016d.png)

Any suggestions would be helpful.

**Comment by will-jl944** [comment]
What's the version of your paddlepaddle? (`pip show paddlepaddle-gpu` or `pip show paddlepaddle`)

**Comment by ZhuoranLyu** [comment]
> What's the version of your paddlepaddle? (`pip show paddlepaddle-gpu` or `pip show paddlepaddle`)

Hi, it's 2.3.0, same as the version in the tutorial.
![1666316443(1)](https://user-images.githubusercontent.com/8801452/197091246-b20c902d-2130-41e1-b20b-60cd88b99539.png)

**Comment by will-jl944** [comment]
This bug is fixed as of paddlepaddle v2.3.1, please follow the steps [here](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html) to install paddlepaddle>=2.3.1.

We'll correct the version specified in the tutorial.

**Comment by ZhuoranLyu** [comment]
ok, thx

**Comment by ZhuoranLyu** [comment]
Another error popped up after upgrading paddlepaddle to 2.3.1.
![1666335742(1)](https://user-images.githubusercontent.com/8801452/197133455-b11316d5-2bca-4275-a2c9-dc5d986f51a0.png)

@will-jl944

**Comment by will-jl944** [comment]
I've reproduced this error using Python 3.10 and paddlepaddle==2.3.1. It seems paddlepaddle's 'dynamic to static' functionality isn't well compatible with Python 3.10. I'll create an issue and report that to [Paddle](https://github.com/paddlepaddle/paddle).

As a quick fix, just downgrade your python to 3.8 or lower, which we've tested.

Thanks for reporting.

**Comment by ZhuoranLyu** [comment]
> 

Thanks for the help~
