### ISSUE TITLE
smoke角度求解问题

### ISSUE THREAD

**Issue by neonhanako** [PaddlePaddle/Paddle3D#117]
Paddle3D代码中，smoke读到的角度是roty，并没有读取alpha（如下图，在paddle3d/transforms/target_generator.py 的 Gt2SmokeTarget 中）。并且后续代码中明确可以看出，角度头回归的就是roty。
![SD%J 1I)@L3GMGWJ5NF~HUA](https://user-images.githubusercontent.com/40436455/197441738-e0b94ade-0cd8-4764-9996-86ec201c6b5d.png)
但是smoke原论文中，是利用alpha对roty进行求解的，回归的对象是alpha，roty为后处理通过alpha计算得到（如下图，在smoke论文第四页）
![image](https://user-images.githubusercontent.com/40436455/197442641-420f2908-e0dc-4956-845b-b4e0991525b0.png)

为什么代码和论文在角度处理上不一样呢？
如果确实是和论文中处理不一样，希望能够在smoke readme上进行说明，防止误导。
非常感谢解答！

**Comment by nepeplwu** [comment]
@neonhanako 感谢反馈和细致的观察，不过这里和论文中的处理是一致的，论文中提到的是回归的目标是 α_z，接着会根据模型预测得到的 α_z 计算出 θ，最终使用 θ 计算Loss，代码中的逻辑可以参考：
1. smoke head predictor：https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/models/detection/smoke/smoke_predictor.py#L95
2. smoke predict decoder：https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/models/detection/smoke/smoke_coder.py#L268
3. 原作者也在他开源的repo中解释过：
    > During training, the ground-truth roty (2) is given. The network predicts the modified observation angle (3). The orientation decoder transforms the modified observation angle (3) to roty (2) and then compute the loss.
  
    详见：https://github.com/lzccccc/SMOKE/issues/13

**Comment by Kerry678231** [comment]
@nepeplwu @neonhanako 我最近也在看角度这块，场景是摄像头是静态的，需要求θ ，本来也想沿用smoke的思路，模型预测α_z（alpha）然后和 theta计算出θ 回归loss，但是这种思路感觉是一个3D思路，通过3d xyz的坐标，回归到2d图像空间，来预测alpha，来反推3d空间的θ，我个人认为这种思路是好的，但是想讨论一下，能不能有更简单的方式，比如我只想要一个θ的输出，有什么更直观的方式吗？
