### ISSUE TITLE
caddn 可视化问题

### ISSUE THREAD

**Issue by MSJYYT** [PaddlePaddle/Paddle3D#123]
用提供的deeplabv3p_resnet101_os8模型前向推理，生成的predbox:9.396643, 5.908683, -0.58069366, 0.7607358, 0.4859006, 1.7858527, 4.660243，理解应该是z,y,x,l,w,h,ry，但是无法用kitti的数据格式可视化；
请问caddn生成的predbox是bev的坐标吗？或者说改怎么处理下才能按照kitti格式可视化呢？

**Comment by wangna11BD** [comment]
模型前向推理生成的并不是kitti的数据格式，还需要进一步后处理，具体后处理在https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/datasets/kitti/kitti_metric.py#L220

**Comment by MSJYYT** [comment]
非常感谢
