### ISSUE TITLE
heat_map radius question

### ISSUE THREAD

**Issue by Kerry678231** [PaddlePaddle/Paddle3D#124]
paddle3d/transforms/target_generator.py line : 304 radius = max(0, int(radius))
我的理解，如果物体像素比如5×5,按照上面计算，只会产生一个1x1的，一个点高斯核，
会不会这样对远处物体或者行人的检出率降低呢，改为
radius = max(1, int(radius))会不会好点呢，纯属自我理解，请帮忙解释一下。。。

**Comment by nepeplwu** [comment]
@Kerry678231 这么改确实对于小目标会友好些，例如[centerpoint](https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/transforms/target_generator.py#L470)就设置为max(2, int(radius))，可以试试验证下，但是应该对精度的影响非常小，因为这类小目标在数据集中也不多

**Comment by Kerry678231** [comment]
了解，感谢。。
