### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by atta007** [PaddlePaddle/Paddle3D#131]
OSError: (External) exclusive_scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered (at /paddle/paddle/fluid/framework/custom_operator.cc:289)
  [operator < hard_voxelize > error]
I am facing this error while training, please guide how to solve this?

![Screenshot from 2022-11-21 16-58-33](https://user-images.githubusercontent.com/39458797/203047783-42ac68ab-85e2-4d6a-b6b8-72ca4caaabf6.png)

**Comment by FlyingQianMM** [comment]
Could you provide more training details to help us reproduce this bug？Like your config file，dataset, and system information.

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
