### ISSUE TITLE
Log file or training configuration of smoke model on waymo dataset.

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [PaddlePaddle/Paddle3D#134]
Hi, I wonder do you guys plan to release the log file or training configuration of the smoke model on waymo dataset for reimplementation.

**Comment by nepeplwu** [comment]
@JiSuanJiDaWang Thank you for your question. There is currently no relevant plan. May I ask why you need to train smoke on Waymo?

**Comment by JiSuanJiDaWang** [comment]
> @JiSuanJiDaWang Thank you for your question. There is currently no relevant plan. May I ask why you need to train smoke on Waymo?

Hi, just want to reimplement the results

**Comment by JiSuanJiDaWang** [comment]
> @JiSuanJiDaWang Thank you for your question. There is currently no relevant plan. May I ask why you need to train smoke on Waymo?

Hi, just want to reimplement the results
