### ISSUE TITLE
ImportError: cannot import name 'nn' from 'paddle.sparse' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/sparse/__init__.py)

### ISSUE THREAD

**Issue by liu-0825** [PaddlePaddle/Paddle3D#136]
pip install .
报错 ImportError: cannot import name 'nn' from 'paddle.sparse' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/sparse/__init__.py)

查看文件确实没有

**Comment by nepeplwu** [comment]
@liu-0825 感谢反馈，请升级到Paddle 2.4版本

**Comment by liu-0825** [comment]
@nepeplwu  ImportError: cannot import name 'sparse' from 'paddle' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py)

paddlepaddle-gpu               2.4.0rc0.post112

还是不行啊

**Comment by liu-0825** [comment]
absl-py                        0.8.1
aiohttp                        3.8.3
aiosignal                      1.3.1
alembic                        1.8.1
altair                         4.2.0
anyio                          3.6.1
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
aspy.yaml                      1.3.0
astor                          0.8.1
astroid                        2.4.1
async-generator                1.10
async-timeout                  4.0.2
asynctest                      0.13.0
attrs                          22.1.0
audioread                      2.1.8
autopep8                       1.6.0
Babel                          2.8.0
backcall                       0.1.0
backports.zoneinfo             0.2.1
bce-python-sdk                 0.8.53
beautifulsoup4                 4.11.1
bleach                         5.0.1
blinker                        1.5
cachetools                     4.0.0
certifi                        2019.9.11
certipy                        0.1.3
cffi                           1.15.1
cfgv                           2.0.1
chardet                        3.0.4
charset-normalizer             2.1.1
click                          8.0.4
cloudpickle                    1.6.0
cma                            2.7.0
colorama                       0.4.4
colorlog                       4.1.0
commonmark                     0.9.1
cryptography                   38.0.1
cycler                         0.10.0
Cython                         0.29
datasets                       2.6.1
debugpy                        1.6.0
decorator                      4.4.2
defusedxml                     0.7.1
descartes                      1.1.0
dill                           0.3.3
easydict                       1.9
entrypoints                    0.4
et-xmlfile                     1.0.1
fastjsonschema                 2.16.1
filelock                       3.0.12
filterpy                       1.4.5
fire                           0.4.0
flake8                         4.0.1
Flask                          1.1.1
Flask-Babel                    1.0.0
Flask-Cors                     3.0.8
forbiddenfruit                 0.1.3
frozenlist                     1.3.3
fsspec                         2022.11.0
funcsigs                       1.0.2
future                         0.18.0
gast                           0.3.3
gitdb                          4.0.5
GitPython                      3.1.14
google-auth                    1.10.0
google-auth-oauthlib           0.4.1
graphviz                       0.13
greenlet                       1.1.3
grpcio                         1.35.0
gunicorn                       20.0.4
gym                            0.12.1
h5py                           2.9.0
huggingface-hub                0.10.1
identify                       1.4.10
idna                           2.8
imageio                        2.6.1
imageio-ffmpeg                 0.3.0
importlib-metadata             4.2.0
importlib-resources            5.9.0
ipykernel                      6.9.1
ipython                        7.34.0
ipython-genutils               0.2.0
ipywidgets                     7.6.5
isort                          4.3.21
itsdangerous                   1.1.0
jdcal                          1.4.1
jedi                           0.17.2
jieba                          0.42.1
Jinja2                         3.0.0
joblib                         0.14.1
JPype1                         0.7.2
json5                          0.9.5
jsonschema                     4.16.0
jupyter                        1.0.0
jupyter-archive                3.2.1
jupyter_client                 7.3.5
jupyter-console                6.4.4
jupyter-core                   4.11.1
jupyter-lsp                    1.5.1
jupyter-server                 1.16.0
jupyter-telemetry              0.1.0
jupyterhub                     1.3.0
jupyterlab                     3.4.5
jupyterlab-language-pack-zh-CN 3.4.post1
jupyterlab-pygments            0.2.2
jupyterlab-server              2.10.3
jupyterlab-widgets             3.0.3
kiwisolver                     1.1.0
lap                            0.4.0
lazy-object-proxy              1.4.3
librosa                        0.7.2
lightgbm                       3.1.1
llvmlite                       0.31.0
lxml                           4.9.1
Mako                           1.2.2
Markdown                       3.1.1
MarkupSafe                     2.0.1
matplotlib                     2.2.3
matplotlib-inline              0.1.6
mccabe                         0.6.1
mistune                        0.8.4
more-itertools                 7.2.0
motmetrics                     1.2.5
moviepy                        1.0.1
multidict                      6.0.2
multiprocess                   0.70.11.1
nbclassic                      0.3.1
nbclient                       0.5.13
nbconvert                      6.4.4
nbformat                       5.5.0
nest-asyncio                   1.5.5
netifaces                      0.10.9
networkx                       2.4
nltk                           3.4.5
nodeenv                        1.3.4
notebook                       5.7.0
numba                          0.48.0
numpy                          1.19.5
nuscenes-devkit                1.1.9
oauthlib                       3.1.0
objgraph                       3.4.1
opencv-python                  4.6.0.66
openpyxl                       3.0.5
opt-einsum                     3.3.0
packaging                      21.3
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.0
paddledet                      2.5.0
paddlefsl                      1.0.0
paddlehub                      2.3.0
paddlenlp                      2.1.1
paddlepaddle-gpu               2.4.0rc0.post112
paddleseg                      2.6.0
pamela                         1.0.0
pandas                         1.1.5
pandocfilters                  1.5.0
parl                           1.4.1
parso                          0.7.1
pathlib                        1.0.1
pexpect                        4.7.0
pickleshare                    0.7.5
Pillow                         8.2.0
pip                            22.3.1
pkgutil_resolve_name           1.3.10
plotly                         5.8.0
pluggy                         1.0.0
pre-commit                     1.21.0
prettytable                    0.7.2
proglog                        0.1.9
prometheus-client              0.14.1
prompt-toolkit                 2.0.10
protobuf                       3.20.0
psutil                         5.7.2
ptyprocess                     0.7.0
py4j                           0.10.9.2
pyarrow                        10.0.0
pyasn1                         0.4.8
pyasn1-modules                 0.2.7
pybboxes                       0.1.1
pyclipper                      1.3.0.post4
pycocotools                    2.0.6
pycodestyle                    2.8.0
pycparser                      2.21
pycryptodome                   3.9.9
pydeck                         0.8.0
pydocstyle                     5.0.2
pyflakes                       2.4.0
pyglet                         1.4.5
Pygments                       2.13.0
pyhumps                        3.8.0
pylint                         2.5.2
Pympler                        1.0.1
pynvml                         8.0.4
pyOpenSSL                      22.0.0
pyparsing                      3.0.9
pypmml                         0.9.11
pyquaternion                   0.9.9
pyrsistent                     0.18.1
python-dateutil                2.8.2
python-json-logger             2.0.4
python-jsonrpc-server          0.3.4
python-language-server         0.33.0
python-lsp-jsonrpc             1.0.0
python-lsp-server              1.5.0
pytz                           2019.3
pytz-deprecation-shim          0.1.0.post0
PyWavelets                     1.3.0
PyYAML                         5.1.2
pyzmq                          23.2.1
qtconsole                      5.4.0
QtPy                           2.3.0
rarfile                        3.1
recordio                       0.1.7
requests                       2.24.0
requests-oauthlib              1.3.0
resampy                        0.2.2
responses                      0.18.0
rich                           12.6.0
rope                           0.17.0
rsa                            4.0
ruamel.yaml                    0.17.21
ruamel.yaml.clib               0.2.6
sahi                           0.10.1
scikit-image                   0.19.3
scikit-learn                   0.24.2
scipy                          1.6.3
seaborn                        0.10.0
semver                         2.13.0
Send2Trash                     1.8.0
sentencepiece                  0.1.96
seqeval                        1.2.2
setuptools                     56.2.0
Shapely                        1.8.5.post1
shellcheck-py                  0.7.1.1
simplegeneric                  0.8.1
six                            1.16.0
sklearn                        0.0
smmap                          3.0.5
sniffio                        1.3.0
snowballstemmer                2.0.0
SoundFile                      0.10.3.post1
soupsieve                      2.3.2.post1
SQLAlchemy                     1.4.41
streamlit                      1.13.0
streamlit-image-comparison     0.0.2
tabulate                       0.8.3
tb-nightly                     1.15.0a20190801
tb-paddle                      0.3.6
tenacity                       8.0.1
tensorboard                    2.1.0
tensorboardX                   1.8
termcolor                      1.1.0
terminado                      0.15.0
terminaltables                 3.1.10
testpath                       0.4.2
threadpoolctl                  2.1.0
tifffile                       2021.11.2
tinycss2                       1.1.1
toml                           0.10.0
toolz                          0.12.0
tornado                        6.2
tqdm                           4.64.1
traitlets                      5.4.0
typed-ast                      1.4.1
typeguard                      2.13.3
typing_extensions              4.3.0
tzdata                         2022.6
tzlocal                        4.2
ujson                          1.35
urllib3                        1.25.11
validators                     0.20.0
virtualenv                     16.7.9
visualdl                       2.4.0
watchdog                       2.1.9
wcwidth                        0.1.7
webencodings                   0.5.1
websocket-client               1.4.1
Werkzeug                       0.16.0
whatthepatch                   1.0.2
wheel                          0.36.2
widgetsnbextension             3.5.2
wrapt                          1.12.1
xarray                         0.16.2
xgboost                        1.3.3
xlrd                           1.2.0
xmltodict                      0.13.0
xxhash                         3.1.0
yapf                           0.26.0
yarl                           1.8.1
zipp                           3.8.1

**Comment by nepeplwu** [comment]
@liu-0825 2.4rc版本是不行的，要安装2.4正式版本
```cmd
python -m pip install paddlepaddle-gpu==2.4.0
```

**Comment by anidagao** [comment]
遇到了一样的问题，升级到正式版2.4也不行。

**Comment by nepeplwu** [comment]
可能是没有安装正确，我这边试了是可以的，建议按照如下方式试试看Paddle的版本，或者先将已经安装的Paddle卸载后重装
```python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.__version__
'2.4.0'
>>> from paddle.sparse import nn
>>> nn
<module 'paddle.sparse.nn' from '/home/ssd6/wuzewu/miniconda3/envs/paddle3d/lib/python3.6/site-packages/paddle/sparse/nn/__init__.py'>
>>> 
```

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
