### ISSUE TITLE
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 3298100352 found).

### ISSUE THREAD

**Issue by liu-0825** [PaddlePaddle/Paddle3D#138]
使用命令：python tools/evaluate.py --config configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml --model output_1/iter_74000/
错误：ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 3298100352 found).
目录下文件：
.iter_74000
├── model.pdopt
└── model.pdparams
ps：模型正常训练完毕

**Comment by wangna11BD** [comment]
python tools/evaluate.py --config configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml --model output_1/iter_74000/model.pdparams
试试呢

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
