### ISSUE TITLE
模型导出报错

### ISSUE THREAD

**Issue by liu-0825** [PaddlePaddle/Paddle3D#139]
命令：python tools/export.py --config configs/caddn/caddn_deeplabv3p_resnet101_os8_kitti.yml --model /output_1/iter_74000/model.pdparams --save_dir Paddle3D-develop/output_1/liu/

错误提示：
  stride = int(spatial_features.shape[2] / x.shape[2])
        ret_dict['spatial_features_%dx' % stride] = x
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        if len(self.deblocks) > 0:
            ups.append(self.deblocks["level_" + str(i)](x))

    TypeError: %d format: a number is required, not Variable

**Comment by wangna11BD** [comment]
测试环境 Ubuntu18.04， CUDA11.2， cuDNN8.1.1，python3.8，paddle2.3是可以正常导出运行出结果的。请问您使用的是什么环境呢～

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
