### ISSUE TITLE
模型导出onnx 算子不支持？

### ISSUE THREAD

**Issue by liu-0825** [PaddlePaddle/Paddle3D#143]
paddle2onnx  --model_dir tools/exported_model/ --model_filename  tools/exported_model/inference.pdmodel --params_filename tools/exported_model/inference.pdiparams --save_file ./model.onnx --enable_dev_version True --opset_version 13 --enable_onnx_checker True
[Paddle2ONNX] Oops, there are some operators not supported yet, including inverse,
[ERROR] Due to the unsupported operators, the conversion is aborted.

inverse算子不支持

**Comment by nepeplwu** [comment]
@liu-0825 这个是因为onnx不支持 inverse 算子导致，可以参考 **[issue60](https://github.com/PaddlePaddle/Paddle3D/issues/60)** 的做法试试看

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
