### ISSUE TITLE
PETR v2 预训练权重

### ISSUE THREAD

**Issue by GlennLoveZhen0124** [PaddlePaddle/Paddle3D#171]
请问是否能提供PETR v2的预训练权重

**Comment by LielinJiang** [comment]
https://paddle3d.bj.bcebos.com/pretrained/fcos3d_vovnet_imgbackbone-remapped.pdparams 预训练的backbone权重。
训练好的模型：https://github.com/PaddlePaddle/Paddle3D/tree/develop/docs/models/petr#%E6%A8%A1%E5%9E%8B%E5%BA%93
