### ISSUE TITLE
centerpoint inference python版本，使用use_trt出现错误

### ISSUE THREAD

**Issue by shuyuan-wang** [PaddlePaddle/Paddle3D#183]
我在使用 https://github.com/PaddlePaddle/Paddle3D/tree/develop/configs/centerpoint 的python inference：
```
python infer.py --model_file /path/to/centerpoint.pdmodel --params_file /path/to/centerpoint.pdiparams --lidar_file /path/to/lidar.pcd.bin --use_trt 1
```
it shows 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/104115572/209793147-b2b50a2e-f7ca-4902-95a2-f914f7c6859d.png">
我需要像c++那样下载预编译库吗？或者需要做些什么吗，这儿显示文件找不到？

**Comment by FlyingQianMM** [comment]
设置`--use_trt 0`时，是否可以正常跑通呢？

**Comment by shuyuan-wang** [comment]
> 设置`--use_trt 0`时，是否可以正常跑通呢？

设置成0没问题

**Comment by shuyuan-wang** [comment]
但是用use_trt是不是应该会比不用inference快？

**Comment by FlyingQianMM** [comment]
如果设置use_trt的话，还是基于Paddle Inferece，内部有使用trt做子图优化。
除了安装最新的Paddle 2.4.1话，还需要下载trt，并且把/path/to/TensorRT/lib/加入到LD_LIBRARY_PATH，版本要求可以看下Paddle Inference文档说明：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/linux-pip.html#erkaishianzhuang

**Comment by shuyuan-wang** [comment]
> 如果设置use_trt的话，还是基于Paddle Inferece，内部有使用trt做子图优化。 除了安装最新的Paddle 2.4.1话，还需要下载trt，并且把/path/to/TensorRT/lib/加入到LD_LIBRARY_PATH，版本要求可以看下Paddle Inference文档说明：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/linux-pip.html#erkaishianzhuang

这个tensorrt版本是需要严格符合的吗？我现在尝试的是cuda11.2+trt8.0.1.6，我下载了trt，并且LD_LIBRARY_PATH也加上去了，但是也就出现了前面的问题
<img width="500" alt="image" src="https://user-images.githubusercontent.com/104115572/209918119-3bbe3fa2-4974-4ab6-a35b-ac6ad536284d.png">

**Comment by ged0606** [comment]
加上`--dynamic_shape_file`应该可以

```
python infer.py --model_file /path/to/centerpoint.pdmodel --params_file /path/to/centerpoint.pdiparams --lidar_file /path/to/lidar.pcd.bin --use_trt 1 --dynamic_shape_file filename
```

**Comment by ged0606** [comment]
问一下, paddle里的sparse conv会有tensorrt加速么

**Comment by FlyingQianMM** [comment]
> > 如果设置use_trt的话，还是基于Paddle Inferece，内部有使用trt做子图优化。 除了安装最新的Paddle 2.4.1话，还需要下载trt，并且把/path/to/TensorRT/lib/加入到LD_LIBRARY_PATH，版本要求可以看下Paddle Inference文档说明：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/linux-pip.html#erkaishianzhuang
> 
> 这个tensorrt版本是需要严格符合的吗？我现在尝试的是cuda11.2+trt8.0.1.6，我下载了trt，并且LD_LIBRARY_PATH也加上去了，但是也就出现了前面的问题 <img alt="image" width="500" src="https://user-images.githubusercontent.com/104115572/209918119-3bbe3fa2-4974-4ab6-a35b-ac6ad536284d.png">

Python开启TensorRT的推理的步骤跟C++ TensorRT部署的步骤一致，所以没有重复写了：https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/docs/models/centerpoint#%E5%BC%80%E5%90%AFtensorrt%E5%8A%A0%E9%80%9F%E9%A2%84%E6%B5%8B%E5%8F%AF%E9%80%89

> 这个tensorrt版本是需要严格符合的吗？

TensorRT版本需要严格对应。建议可以使用Paddle官方docker，这样不需要再手动安装trt了。

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by FlyingQianMM** [comment]
> 问一下, paddle里的sparse conv会有tensorrt加速么

目前还没有TensorRT加速。想问下现在CenterPoint spconv版本的推理速度满足您的场景要求吗？如果不满足的话，差距还有多少？

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue

**Comment by yaobaishen** [comment]
> 加上`--dynamic_shape_file`应该可以
> 
> ```
> python infer.py --model_file /path/to/centerpoint.pdmodel --params_file /path/to/centerpoint.pdiparams --lidar_file /path/to/lidar.pcd.bin --use_trt 1 --dynamic_shape_file filename
> ```

@ged0606 能否问下这个dynamic_shape_file如何得到呢？我遇到了同样的问题

**Comment by yaobaishen** [comment]
> > 加上`--dynamic_shape_file`应该可以
> > ```
> > python infer.py --model_file /path/to/centerpoint.pdmodel --params_file /path/to/centerpoint.pdiparams --lidar_file /path/to/lidar.pcd.bin --use_trt 1 --dynamic_shape_file filename
> > ```
> 
> @ged0606 能否问下这个dynamic_shape_file如何得到呢？我遇到了同样的问题

Update: from the [guide](https://github.com/ApolloAuto/apollo-model-centerpoint/tree/master/docs/models/centerpoint) when running the TRT mode for the first time, use below command:
```
python deploy/centerpoint/python/infer.py --model_file models/center_point_paddle/centerpoint.pdmodel --params_file models/center_point_paddle/centerpoint.pdiparams --lidar_file xxx.point_cloud.bin --num_point_dim 4 --collect_shape_info 1 --dynamic_shape_file center_point_shape_info.txt --use_trt 1
```
