### ISSUE TITLE
训练好模型进行test时报错

### ISSUE THREAD

**Issue by 963yms** [PaddlePaddle/Paddle3D#206]
1.模型训练好后，根据Readme.md直接python tools/plain_train_net.py --eval-only --config-file "configs/smoke_gn_vector.yaml"会报错
![image](https://user-images.githubusercontent.com/111960298/210744667-cdcc60b6-7aa4-4d36-b588-5c22a1e7e3bc.png)
如何解决？
2.若直接将问题1的报错信息cfg.merge_from_list(args.opts)注释掉，报错（没有该文件夹及文件，需要自己创建吗）
![image](https://user-images.githubusercontent.com/111960298/210745870-0b3eaec8-9b1c-4589-a8f2-fc5c7e8a3440.png)

**Comment by Birdylx** [comment]
@963yms hi，你似乎跑的是原作者的代码库[https://github.com/lzccccc/SMOKE](https://github.com/lzccccc/SMOKE)，可以根据Paddle3D的[README](https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/docs/models/smoke)试试SMOKE模型。

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
