### ISSUE TITLE
训练自己采集的激光雷达点云数据，但没有的对应图片数据，在calib文件中应该怎么填写信息比较合适呢？

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/Paddle3D#211]
作者您好，我想使用pointpilliars训练自己采集的点云数据，但是没有对应的图片，也没有相关的相机参数信息，那么训练前准备数据时在calib文件中的坐标系转换参数，如：P2，R0_rect，Tr_velo_to_cam，Tr_imu_to_velo 应该怎么填写比较合适，会不会影响训练效果呢？

**Comment by FlyingQianMM** [comment]
Pointpillars是纯点云的检测模型，自行训练的话，跟相机和IMU相关的参数可以设置维为虚假值。

目前适配的KITTI数据集的真值是相对于相机坐标系的，所以需要把预测结果转换到相机坐标系才能完成精度评估。如果是自己的数据集，可以修改数据读取和精度评估的部分，只需要在Lidar坐标系下进行即可。

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
