### ISSUE TITLE
SMOKE@Rope3D 模型评估结果异常，所有结果均为零。

### ISSUE THREAD

**Issue by Luna2199** [PaddlePaddle/Paddle3D#217]
评估结果异常，全零。
![1673577264644](https://user-images.githubusercontent.com/21285692/212223931-d27edbdb-bcdb-462e-a810-00afd2ff7d76.png)

**请教大佬，针对SMOKE@Rope3D数据集的评估结果异常，是什么原因导致的？**

**Comment by nepeplwu** [comment]
模型训练过程中loss是否正常收敛？

**Comment by Luna2199** [comment]
> 模型训练过程中loss是否正常收敛？

![1673587009275](https://user-images.githubusercontent.com/21285692/212243009-eb9d7661-9976-42e6-82dc-015b8084c52c.png)
total_loss很快就能收敛到极小的值，是不是也不正常？
