### ISSUE TITLE
训练模型视觉感知算法示例出错

### ISSUE THREAD

**Issue by TreasureYi** [PaddlePaddle/Paddle3D#221]
LAUNCH INFO 2023-01-18 09:37:50,220 ------------------------- ERROR LOG DETAIL -------------------------
platform:
    Windows-10-10.0.19044-SP0
    Not Found.
    Python - 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]

Science Toolkits:
    cv2 - 4.5.5
    numpy - 1.23.5
    numba - 0.56.4
    pandas - 1.5.2
    pillow - 8.3.2
    skimage - 0.19.3

PaddlePaddle:
    paddle(gpu) - 2.4.1
    paddle3d - 1.0.0
    paddleseg - 2.7.0
    FLAGS_cudnn_deterministic - Not set.
    FLAGS_cudnn_exhaustive_search - Not set.

CUDA:
    cudnn - 7605
    nvcc - Cuda compilation tools, release 10.2, V10.2.89

GPUs:
------------------------------------------------
W0118 09:37:23.710577 10232 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Ru
ntime API Version: 10.2
W0118 09:37:23.710577 10232 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
2023-01-18 09:37:29 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2023-01-18 09:37:31 [INFO]      There are 1525/1525 variables loaded into HRNet.
E:\develop\miniconda3\conda-data\conda-env\paddle_env\lib\site-packages\paddle\nn\layer\norm.py:711: UserWarning: When training, w
e now always track global mean and variance.
  warnings.warn(
LAUNCH INFO 2023-01-18 09:37:50,249 Exit code 3221226505

**Comment by TreasureYi** [comment]
看提示的是Windows-10-10.0.19044-SP0 Not Found 和 FLAGS_cudnn_deterministic - Not set 这个要如何解决啊

**Comment by FlyingQianMM** [comment]
麻烦提供下运行指令，完整的日志，机器环境、Paddle版本、以及相对于原始代码的修改项。

**Comment by TreasureYi** [comment]
win10 cuda10.2 cudnn7.6 paddlepaddle-gpu==2.4.1

python -m paddle.distributed.launch tools/train.py --config configs/smoke/smoke_hrnet18_no_dcn_kitti_mini.yml --num_workers 2 --log_interval 50 --save_interval 2000 --save_dir output_smoke_kitti



LAUNCH INFO 2023-01-18 10:26:36,951 -----------  Configuration  ----------------------
LAUNCH INFO 2023-01-18 10:26:36,951 devices: None
LAUNCH INFO 2023-01-18 10:26:36,951 elastic_level: -1
LAUNCH INFO 2023-01-18 10:26:36,951 elastic_timeout: 30
LAUNCH INFO 2023-01-18 10:26:36,952 gloo_port: 6767
LAUNCH INFO 2023-01-18 10:26:36,952 host: None
LAUNCH INFO 2023-01-18 10:26:36,952 ips: None
LAUNCH INFO 2023-01-18 10:26:36,952 job_id: default
LAUNCH INFO 2023-01-18 10:26:36,952 legacy: False
LAUNCH INFO 2023-01-18 10:26:36,952 log_dir: log
LAUNCH INFO 2023-01-18 10:26:36,953 log_level: INFO
LAUNCH INFO 2023-01-18 10:26:36,953 master: None
LAUNCH INFO 2023-01-18 10:26:36,953 max_restart: 3
LAUNCH INFO 2023-01-18 10:26:36,953 nnodes: 1
LAUNCH INFO 2023-01-18 10:26:36,954 nproc_per_node: None
LAUNCH INFO 2023-01-18 10:26:36,955 rank: -1
LAUNCH INFO 2023-01-18 10:26:36,955 run_mode: collective
LAUNCH INFO 2023-01-18 10:26:36,955 server_num: None
LAUNCH INFO 2023-01-18 10:26:36,955 servers:
LAUNCH INFO 2023-01-18 10:26:36,955 start_port: 6070
LAUNCH INFO 2023-01-18 10:26:36,956 trainer_num: None
LAUNCH INFO 2023-01-18 10:26:36,956 trainers:
LAUNCH INFO 2023-01-18 10:26:36,956 training_script: tools/train.py
LAUNCH INFO 2023-01-18 10:26:36,956 training_script_args: ['--config', 'configs/smoke/smoke_hrnet18_no_dcn_kitti_mini.yml', '--num
_workers', '0', '--log_interval', '50', '--save_interval', '50', '--save_dir', 'output_smoke_kitti']
LAUNCH INFO 2023-01-18 10:26:36,956 with_gloo: 1
LAUNCH INFO 2023-01-18 10:26:36,956 --------------------------------------------------
LAUNCH INFO 2023-01-18 10:26:36,958 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-01-18 10:26:36,959 Run Pod: gcwgsn, replicas 1, status ready
LAUNCH INFO 2023-01-18 10:26:36,982 Watching Pod: gcwgsn, replicas 1, status running
2023-01-18 10:26:43,223 -     INFO -
------------Environment Information-------------
platform:
    Windows-10-10.0.19044-SP0
    Not Found.
    Python - 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)]

Science Toolkits:
    cv2 - 4.5.5
    numpy - 1.23.5
    numba - 0.56.4
    pandas - 1.5.2
    pillow - 8.3.2
    skimage - 0.19.3

PaddlePaddle:
    paddle(gpu) - 2.4.1
    paddle3d - 1.0.0
    paddleseg - 2.7.0
    FLAGS_cudnn_deterministic - Not set.
    FLAGS_cudnn_exhaustive_search - Not set.

CUDA:
    cudnn - 7605
    nvcc - Cuda compilation tools, release 10.2, V10.2.89

GPUs:
------------------------------------------------
2023-01-18 10:26:43,230 -     INFO -
---------------Config Information---------------
batch_size: 8
export:
  transforms:
  - reader: pillow
    to_chw: false
    to_rgb: true
    type: LoadImage
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: Normalize
iters: 10000
lr_scheduler:
  learning_rate: 0.000125
  milestones:
  - 5000
  - 8000
  type: MultiStepDecay
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
    type: $paddleseg.HRNet_W18
  depth_ref:
  - 28.01
  - 16.32
  dim_ref:
  - - 3.88
    - 1.63
    - 1.53
  - - 1.78
    - 1.7
    - 0.58
  - - 0.88
    - 1.73
    - 0.67
  head:
    in_channels: 270
    norm_type: gn
    num_chanels: 256
    num_classes: 3
    reg_channels:
    - 1
    - 2
    - 3
    - 2
    - 2
    type: SMOKEPredictor
  max_detection: 50
  pred_2d: true
  type: SMOKE
optimizer:
  type: Adam
train_dataset:
  dataset_root: datasets/KITTI
  mode: train
  transforms:
  - reader: pillow
    to_chw: false
    type: LoadImage
  - input_size:
    - 1280
    - 384
    mode: train
    num_classes: 3
    type: Gt2SmokeTarget
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: Normalize
  type: KittiMonoDataset
val_dataset:
  dataset_root: datasets/KITTI
  mode: val
  transforms:
  - reader: pillow
    to_chw: false
    type: LoadImage
  - input_size:
    - 1280
    - 384
    mode: val
    num_classes: 3
    type: Gt2SmokeTarget
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: Normalize
  type: KittiMonoDataset
------------------------------------------------
W0118 10:26:43.231799 15084 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Ru
ntime API Version: 10.2
W0118 10:26:43.232419 15084 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
2023-01-18 10:26:45 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2023-01-18 10:26:46 [INFO]      There are 1525/1525 variables loaded into HRNet.
E:\develop\miniconda3\conda-data\conda-env\paddle_env\lib\site-packages\paddle\nn\layer\norm.py:711: UserWarning: When training, w
e now always track global mean and variance.
  warnings.warn(
E:\develop\miniconda3\conda-data\conda-env\paddle_env\lib\site-packages\paddle\nn\layer\norm.py:711: UserWarning: When training, w
e now always track global mean and variance.
  warnings.warn(
LAUNCH INFO 2023-01-18 10:27:13,315 Pod failed
LAUNCH ERROR 2023-01-18 10:27:13,315 Container failed !!!
Container rank 0 status failed cmd ['E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env\\python.exe', '-u', 'tools/train.p
y', '--config', 'configs/smoke/smoke_hrnet18_no_dcn_kitti_mini.yml', '--num_workers', '0', '--log_interval', '50', '--save_interva
l', '50', '--save_dir', 'output_smoke_kitti'] code 3221226505 log log\workerlog.0
env {'__INTELLIJ_COMMAND_HISTFILE__': 'C:\\Users\\LY\\AppData\\Local\\JetBrains\\PyCharmCE2021.1\\terminal\\history\\Paddle3D-hist
ory', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'NVCUDASAMPLES_ROOT':
 'E:\\develop\\cuda-data\\samples', 'PROGRAMDATA': 'C:\\ProgramData', 'COMPUTERNAME': 'P0192389', 'SYSTEMDRIVE': 'C:', 'USERDOMAIN
': 'P0192389', 'CUDA_PATH': 'E:\\develop\\cuda-data\\v10.2', 'ONEDRIVE': 'C:\\Users\\LY\\OneDrive', 'COMMONPROGRAMFILES(X86)': 'C:
\\Program Files (x86)\\Common Files', 'TMP': 'C:\\Users\\LY\\AppData\\Local\\Temp', 'TEMP': 'C:\\Users\\LY\\AppData\\Local\\Temp',
 'PROGRAMFILES': 'C:\\Program Files', 'USERDOMAIN_ROAMINGPROFILE': 'P0192389', 'WINDIR': 'C:\\WINDOWS', 'CUDA_PATH_V10_2': 'E:\\de
velop\\cuda-data\\v10.2', 'PROCESSOR_LEVEL': '6', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'JAVA_HOME': 'E:\\develop\\jdk8-341
', 'NUMBER_OF_PROCESSORS': '12', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'OS': 'Windows_NT', 'NVTOOLSEXT_PATH': 'C:\\Program Files\\NVI
DIA Corporation\\NvToolsExt\\', 'ASL.LOG': 'Destination=file', 'PROMPT': '(E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_
env) $P$G', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'CONDA_PROMPT_MODIFIER': '(E:\\develop\\miniconda3\\conda-data\\conda-
env\\paddle_env) ', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\
\Modules', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6
Model 166 Stepping 0, GenuineIntel', 'APPDATA': 'C:\\Users\\LY\\AppData\\Roaming', 'WXDRIVE_START_ARGS': '--wxdrive-setting=0 --di
sable-gpu --disable-software-rasterizer --enable-features=NetworkServiceInProcess', 'GRADLE_HOME': 'E:\\develop\\gradle-7.4.1', 'L
OCALAPPDATA': 'C:\\Users\\LY\\AppData\\Local', 'CYGWIN': 'mintty', 'GRADLE_USER_HOME': 'E:\\develop\\gradle-7.4.1\\repository', 'V
S140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\', 'SYSTEMROOT': 'C:\\WINDOWS', 'HOMEPATH'
: '\\Users\\LY', 'CONDA_PREFIX': 'E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env', 'TERMINAL_EMULATOR': 'JetBrains-Jed
iTerm', 'GROOVY_HOME': 'E:\\develop\\apache-groovy-sdk-3.0.11\\groovy-3.0.11', 'LOGONSERVER': '\\\\P0192389', 'SESSIONNAME': 'Cons
ole', 'HOMEDRIVE': 'C:', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'PATH': 'C:\\Users\\LY\\AppData\\Roaming\\Pyt
hon\\Python38\\site-packages\\cv2\\../../x64/vc14/bin;E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env\\lib\\site-packag
es\\paddle\\fluid;E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env\\lib\\site-packages\\paddle\\fluid\\..\\libs;E:\\deve
lop\\miniconda3\\conda-data\\conda-env\\paddle_env;E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env\\Library\\mingw-w64\
\bin;E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env\\Library\\usr\\bin;E:\\develop\\miniconda3\\conda-data\\conda-env\
\paddle_env\\Library\\bin;E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env\\Scripts;E:\\develop\\miniconda3\\conda-data\
\conda-env\\paddle_env\\bin;E:\\develop\\miniconda3\\condabin;E:\\develop\\cuda-data\\v10.2\\bin;E:\\develop\\cuda-data\\v10.2\\li
bnvvp;.;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;E:\\develop\\python\\Scripts;E:\\develop\\python;C:\\Program
Data\\Oracle\\Java\\javapath;E:\\develop\\jdk8-341\\bin;E:\\develop\\apache-groovy-sdk-3.0.11\\groovy-3.0.11\\bin;C:\\Windows\\sys
tem32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Pr
ogram Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;E:\\develop\\MySQL\\bin
;E:\\develop\\apache-maven-3.5.4\\bin;E:\\develop\\gradle-7.4.1\\bin;E:\\develop\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\W
INDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;E:\\develop\\wechatdevtool\\
寰\ue1bb俊web寮€鍙戣€呭伐鍏穃dll;E:\\develop\\nodejs;E:\\develop\\sonar-scanner-cli-4.7.0.2747-windows\\sonar-scanner-4.7.0.2747
-windows\\bin;E:\\develop\\miniconda3;E:\\develop\\miniconda3\\Scripts;E:\\develop\\miniconda3\\Library\\bin;E:\\develop\\minicond
a3\\bin;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit;C:\\Program Files\\NVIDIA Corporation\\Nsight Comp
ute 2019.5.0;C:\\Users\\LY\\AppData\\Local\\Microsoft\\WindowsApps;.;C:\\Users\\LY\\AppData\\Local\\Programs\\Microsoft VS Code\\b
in;E:\\develop\\Microsoft-VS-Code\\Microsoft VS Code\\bin', 'PUBLIC': 'C:\\Users\\Public', 'ROCKETMQ_HOME': 'E:\\develop\\rocketmq
-all-4.5.0-bin-release', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'MAVEN_HOME': 'E:\\develop\\apache-maven-3.5.4', '
IDEA_INITIAL_DIRECTORY': 'E:\\develop\\PyCharm Community Edition 2021.1.1\\bin', 'PROCESSOR_REVISION': 'a600', 'USERPROFILE': 'C:\
\Users\\LY', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'USERNAME': 'LY', 'CONDA_SHLVL': '
1', 'CONDA_DEFAULT_ENV': 'E:\\develop\\miniconda3\\conda-data\\conda-env\\paddle_env', 'PROGRAMW6432': 'C:\\Program Files', 'COMMO
NPROGRAMW6432': 'C:\\Program Files\\Common Files', 'TERM_SESSION_ID': 'bf75e813-2450-4793-8068-d3ebeeb7c108', 'NVCUDASAMPLES10_2_R
OOT': 'E:\\develop\\cuda-data\\samples', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'POD_NAME': 'gcwgsn', 'PADDLE_MASTER':
'172.16.71.136:44645', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', '
PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '172.16.71.136:44646', 'PADDLE_CURRENT_ENDPOINT': '172.16.71.136:44646', 'PADDLE_
TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2023-01-18 10:27:13,317 ------------------------- ERROR LOG DETAIL -------------------------
 - 1.5.2
    pillow - 8.3.2
    skimage - 0.19.3

PaddlePaddle:
    paddle(gpu) - 2.4.1
    paddle3d - 1.0.0
    paddleseg - 2.7.0
    FLAGS_cudnn_deterministic - Not set.
    FLAGS_cudnn_exhaustive_search - Not set.

CUDA:
    cudnn - 7605
    nvcc - Cuda compilation tools, release 10.2, V10.2.89

GPUs:
------------------------------------------------
2023-01-18 10:26:43,230 -     INFO -
---------------Config Information---------------
batch_size: 8
export:
  transforms:
  - reader: pillow
    to_chw: false
    to_rgb: true
    type: LoadImage
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: Normalize
iters: 10000
lr_scheduler:
  learning_rate: 0.000125
  milestones:
  - 5000
  - 8000
  type: MultiStepDecay
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
    type: $paddleseg.HRNet_W18
  depth_ref:
  - 28.01
  - 16.32
  dim_ref:
  - - 3.88
    - 1.63
    - 1.53
  - - 1.78
    - 1.7
    - 0.58
  - - 0.88
    - 1.73
    - 0.67
  head:
    in_channels: 270
    norm_type: gn
    num_chanels: 256
    num_classes: 3
    reg_channels:
    - 1
    - 2
    - 3
    - 2
    - 2
    type: SMOKEPredictor
  max_detection: 50
  pred_2d: true
  type: SMOKE
optimizer:
  type: Adam
train_dataset:
  dataset_root: datasets/KITTI
  mode: train
  transforms:
  - reader: pillow
    to_chw: false
    type: LoadImage
  - input_size:
    - 1280
    - 384
    mode: train
    num_classes: 3
    type: Gt2SmokeTarget
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: Normalize
  type: KittiMonoDataset
val_dataset:
  dataset_root: datasets/KITTI
  mode: val
  transforms:
  - reader: pillow
    to_chw: false
    type: LoadImage
  - input_size:
    - 1280
    - 384
    mode: val
    num_classes: 3
    type: Gt2SmokeTarget
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: Normalize
  type: KittiMonoDataset
------------------------------------------------
W0118 10:26:43.231799 15084 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Ru
ntime API Version: 10.2
W0118 10:26:43.232419 15084 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
2023-01-18 10:26:45 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2023-01-18 10:26:46 [INFO]      There are 1525/1525 variables loaded into HRNet.
E:\develop\miniconda3\conda-data\conda-env\paddle_env\lib\site-packages\paddle\nn\layer\norm.py:711: UserWarning: When training, w
e now always track global mean and variance.
  warnings.warn(
E:\develop\miniconda3\conda-data\conda-env\paddle_env\lib\site-packages\paddle\nn\layer\norm.py:711: UserWarning: When training, w
e now always track global mean and variance.
  warnings.warn(
LAUNCH INFO 2023-01-18 10:27:13,340 Exit code 3221226505


代码未修改，按照官网的步骤执行的

**Comment by FlyingQianMM** [comment]
'''
LAUNCH INFO 2023-01-18 10:27:13,315 Pod failed
LAUNCH ERROR 2023-01-18 10:27:13,315 Container failed !!!
Container rank 0 status failed cmd ['E:\develop\miniconda3\conda-data\conda-env\paddle_env\python.exe', '-u', 'tools/train.p
y', '--config', 'configs/smoke/smoke_hrnet18_no_dcn_kitti_mini.yml', '--num_workers', '0', '--log_interval', '50', '--save_interva
l', '50', '--save_dir', 'output_smoke_kitti'] code 3221226505 log log\workerlog.0
env {'INTELLIJ_COMMAND_HISTFILE': 'C:\Users\LY\AppData\Local\JetBrains\PyCharmCE2021.1\terminal\history\Paddle3D-hist
ory', 'COMMONPROGRAMFILES': 'C:\Program Files\Common Files', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'NVCUDASAMPLES_ROOT':
'''

看着像是你环境的问题，看下log/worker0.log的日志信息。另外不要在pycharm里面启动训练，试下直接在终端启动python训练
