### ISSUE TITLE
model debug infer 如何跳到模型结构处呢

### ISSUE THREAD

**Issue by Kerry678231** [PaddlePaddle/Paddle3D#239]
如题请教一下：
比如debug 运行如下代码
deploy/centerpoint/python/infer.py
等模型推理跑前向的时候如何跳到模型里面呢？请问如何设置或者发下参考代码

**Comment by FlyingQianMM** [comment]
推理阶段的静态图模型无法跳入模型里面。debug的话，可以基于动态图，参考评估阶段

**Comment by Kerry678231** [comment]
好的。了解了
