### ISSUE TITLE
当使用pointpilliars进行模型训练及验证时,出现了iou3d_nms_cuda builded fail问题

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/Paddle3D#242]
当使用pointpilliars进行模型训练及验证时，出现了如下报错： 
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /home/les/.cache/paddle_extensions && /home/les/miniconda3/envs/paddle3d_cuda11.6/bin/python iou3d_nms_cuda_setup.py build' returned non-zero exit status 1.
我的环境是：
ubuntu18.04，cuda11.6,  cuDNN Version: 8.4，python3.8
查看了paddle3d文件夹下的opt文件中没有 iou3d_nms_cuda相关的文件，可能是在安装的时候有哪些漏掉了，
请问怎么解决呢？

**Comment by FlyingQianMM** [comment]
iou3d_nms_cuda是Paddle3D的自定义算子，一般会安装在/home/les/.cache/paddle_extensions目录下。
目前Paddle3D训练过程中自定义算子走的是即时编译，可以删除这个目录下的自定义算子，重新跑下试试看。

另外在Linux下，建议您使用Paddle官方镜像，在该镜像的容器里面使用Paddle3D，这样可以避免环境版本互相不匹配导致的未知bug。CUDA116下面也可以使用Paddle cuda112的镜像：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by cxy86121** [comment]
好的明白了，谢谢回答！

**Comment by natsume7** [comment]
> iou3d_nms_cuda是Paddle3D的自定义算子，一般会安装在/home/les/.cache/paddle_extensions目录下。 目前Paddle3D训练过程中自定义算子走的是即时编译，可以删除这个目录下的自定义算子，重新跑下试试看。
> 
> 另外在Linux下，建议您使用Paddle官方镜像，在该镜像的容器里面使用Paddle3D，这样可以避免环境版本互相不匹配导致的未知bug。CUDA116下面也可以使用Paddle cuda112的镜像：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

你好，在该文件夹下会生成iou3d_nms_cuda_setup.py，删除后运行会重新生成并依然报错

**Comment by cxy86121** [comment]
应该是cuda 环境变量有问题：
先创建软连接：sudo ln -s /usr/local/cuda-xx (你的cuda版本) /usr/local/cuda
bashrc文件中添加环境变量：
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH
保存退出后终端分别执行
source ~/.bashrc
ldconfig
然后再重启电脑

**Comment by cxy86121** [comment]
> > iou3d_nms_cuda是Paddle3D的自定义算子，一般会安装在/home/les/.cache/paddle_extensions目录下。 目前Paddle3D训练过程中自定义算子走的是即时编译，可以删除这个目录下的自定义算子，重新跑下试试看。
> > 另外在Linux下，建议您使用Paddle官方镜像，在该镜像的容器里面使用Paddle3D，这样可以避免环境版本互相不匹配导致的未知bug。CUDA116下面也可以使用Paddle cuda112的镜像：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
> 
> 你好，在该文件夹下会生成iou3d_nms_cuda_setup.py，删除后运行会重新生成并依然报错

应该是cuda 环境变量有问题：
先创建软连接：sudo ln -s /usr/local/cuda-xx (你的cuda版本) /usr/local/cuda
bashrc文件中添加环境变量：
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH
保存退出后终端分别执行
source ~/.bashrc
ldconfig
然后再重启电脑

**Comment by XYC0101** [comment]
请问windows系统上出现这种情况该如何解决

**Comment by cxy86121** [comment]
没有在windows上试过，但应该也是环境变量设置的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月19日(星期三) 上午9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle3D] 当使用pointpilliars进行模型训练及验证时,出现了iou3d_nms_cuda builded fail问题 (Issue #242)





 
请问windows系统上出现这种情况该如何解决

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
