### ISSUE TITLE
pointpillars训练的模型如何转换成onnx

### ISSUE THREAD

**Issue by rainaider** [PaddlePaddle/Paddle3D#247]
这是我的命令：
paddle2onnx  --model_dir /paddle/exported_model  --model_filename pointpillars.pdmodel --params_filename pointpillars.pdiparams  --save_file pointpillars.onnx

以下是报错：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /paddle/exported_model/pointpillars.pdmodel
[Paddle2ONNX] Paramters file path: /paddle/exported_model/pointpillars.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including bitwise_and,bitwise_xor,conditional_block,empty,index_sample,nms_gpu,select_input,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)

**Comment by FlyingQianMM** [comment]
pointpillars里面有自定义算子nms，onnx没有这个自定义算子实现，无法转onnx。

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
