### ISSUE TITLE
centerpoint_postprocess question

### ISSUE THREAD

**Issue by Kerry678231** [PaddlePaddle/Paddle3D#248]
bboxes, scores, labels = centerpoint_postprocess.centerpoint_postprocess(
          hm, reg, height, dim, vel, rot, test_cfg.voxel_size,
          test_cfg.point_cloud_range, test_cfg.post_center_limit_range,
          num_classes, test_cfg.down_ratio, test_cfg.score_threshold,
          test_cfg.nms.nms_iou_threshold, test_cfg.nms.nms_pre_max_size,
          test_cfg.nms.nms_post_max_size, self.with_velocity)

from paddle3d.ops import centerpoint_postprocess

如上代码，这个centerpoint_postprocess的函数已经包装成算子了，能否提供一下详细的实现方式呢，或者资料呢

**Comment by justld** [comment]
你好，可以参考：https://github.com/PaddlePaddle/Paddle3D/blob/8626ff50616ce6a94ad5236c08d1cc8c5d8b41a6/paddle3d/ops/centerpoint_postprocess/postprocess.cu#L104

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
