### ISSUE TITLE
nuscenes训练smoke

### ISSUE THREAD

**Issue by Lyric0620** [PaddlePaddle/Paddle3D#249]
请问如何用nuscenes数据集对smoke进行训练

**Comment by justld** [comment]
参考已有的yml配置文件，修改数据集部分的设置，可以参考：
https://github.com/PaddlePaddle/Paddle3D/blob/release/1.0/docs/configuration.md

**Comment by Lyric0620** [comment]
@justld 请问smoke配置文件里的  `reg_channels` 是什么含义

**Comment by nepeplwu** [comment]
@Yutong-gannis reg_channels用于配置SMOKE Head中回归的channels数量，和数据集无关，不需要修改，主要含义：
* 0：depths_offset
* 1 ~ 2：proj_offsets
* 3 ~ 5：dimensions_offsets
* 6 ~ 7：orientation
* 8 ~ 9：bboxsize

可以参考这里的代码：https://github.com/PaddlePaddle/Paddle3D/blob/release/1.0/paddle3d/models/detection/smoke/smoke_loss.py#L97

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
