### ISSUE TITLE
导出SqueezeSegV3的.pdmodel或者.onnx

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle3D#251]
我想可视化SqueezeSegV3的结构，但发现最终保存的不是.pdmodel，我要怎么才能可视化SqueezeSegV3的结构

**Comment by will-jl944** [comment]
训练过程中只会保存用于恢复训练的`.pdparams`模型参数文件以及`.pdopt`优化器参数文件。

如果需要查看模型结构，需要将模型导出（参考 https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/docs/models/squeezesegv3#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA ），得到`.pdmodel`文件。
