### ISSUE TITLE
IASSD模型推理预测可视化效果与数据不匹配

### ISSUE THREAD

**Issue by xd-Nanan** [PaddlePaddle/Paddle3D#254]
你好，我使用IASSD模型对kitti 64线数据集进行训练，然后进行推理预测并可视化，但预测出的数据与点云信息并不匹配，使用本项目官方给出的权重文件进行推理预测的结果同样，如下图所示（使用官方权重文件进行推理预测可视化的结果，针对score使用一定阈值让其可视化4个box），是推理预测的代码没完善吗？
![image](https://user-images.githubusercontent.com/52264659/220799246-30e12b1d-926a-4b5f-9513-aab6cc85e741.png)

![image](https://user-images.githubusercontent.com/52264659/220798665-a3c91bff-a92a-45cc-b112-aca14e135a0c.png)

**Comment by Birdylx** [comment]
@xd-Nanan hi，这是坐标系和box坐标格式的问题，推理代码给出的是模型nms后的bbox，这个bbox坐标在格式上和用于eval的坐标有些许不同，代码在[这里](https://github.com/PaddlePaddle/Paddle3D/blob/8626ff50616ce6a94ad5236c08d1cc8c5d8b41a6/paddle3d/models/detection/iassd/iassd.py#L228)进行了转换，你可以采用转换后的坐标进行可视化。
