### ISSUE TITLE
怎么在KITTI test set上评测

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle3D#255]
centerpoint和pointpillars都给了KITTI val test上的分数，我理解val test上的分数是用3K帧训练集训练之后得到的，一般论文中KITTI test set上的分数是在6K帧训练集+验证集上训练得到的，不知道理解的对不对。目前centerpoint和pointpillars都只有KITTI val test上的分数，为什么没有KITTI test set的分数，是只能把结果提交到KITTI官方才能得到吗？

**Comment by justld** [comment]
你好，需要将测试集的预测结果提交到官网进行精度验证。

**Comment by kamiLight** [comment]
paddle3d有提供生成测试集预测结果的代码吗

**Comment by justld** [comment]
您好，暂时没有测试集预测结构生成代码。
