### ISSUE TITLE
日志文件乱码&日志文件名如何设置？

### ISSUE THREAD

**Issue by Xiaolong-RRL** [PaddlePaddle/Paddle3D#257]
在使用Paddle3D-1.0训练SMOKE时，发现保存的日志文件全是乱码：

![微信截图_20230307202445](https://user-images.githubusercontent.com/74476562/223421419-d66a85f2-8e5d-4516-bc21-85e25102a2ad.png)

运行的环境信息如下所示：
```
platform:
    Linux-5.4.0-132-generic-x86_64-with-glibc2.17
    gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    Python - 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
Science Toolkits:
    cv2 - 4.5.5
    numpy - 1.21.5
    numba - 0.56.3
    pandas - 1.3.5
    pillow - 8.3.2
    skimage - 0.19.2
PaddlePaddle:
    paddle(gpu) - 2.4.1
    paddle3d - 1.0.0
    paddleseg - 2.7.0
    FLAGS_cudnn_deterministic - Not set.
    FLAGS_cudnn_exhaustive_search - Not set.
CUDA:
    cudnn - 7605
    nvcc - Cuda compilation tools, release 10.2, V10.2.89
```

请问这个问题如何解决？

另外，日志文件的文件名该如何自定义呢？

谢谢~

**Comment by Birdylx** [comment]
@Xiaolong-RRL hi，日志保存在log目录下，自定义日志可以用输出重定向：
```shell
nohup python tools/train.py --config configs/xxx &> train_exp1.log &
```

**Comment by Xiaolong-RRL** [comment]
> @Xiaolong-RRL hi，日志保存在log目录下，自定义日志可以用输出重定向：
> 
> ```shell
> nohup python tools/train.py --config configs/xxx &> train_exp1.log &
> ```

感谢你的回答~我尝试过没有问题的，但仍然很困惑为什么使用paddle3d-1.0源码训练保存的日志是乱码？

**Comment by Birdylx** [comment]
也许和你的平台环境有关。
