### ISSUE TITLE
【黑客松第四期 No.166】3D目标检测可视化

### ISSUE THREAD

**Issue by lizechng** [PaddlePaddle/Paddle3D#261]
您好，[pr](https://github.com/PaddlePaddle/Paddle3D/pull/256) 已经提交一段时间了，想问一下评审结果，是否需要进行修改

**Comment by Birdylx** [comment]
@lizechng hi，我们会尽快review

**Comment by Birdylx** [comment]
Since the author closed the PR #256, issue closed for now.
