### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle3D#265]
bevformer模型导出静态图报错
![image](https://user-images.githubusercontent.com/37332773/224321638-6ca54e5a-4ad3-4586-bd08-d1ef61061c8d.png)

环境：
device: AIStudio/CPU
paddle: 2.4.0
使用命令：
`python tools/export.py --config configs/bevformer/bevformer_tiny_r50_fpn_nuscenes.yml --model https://paddle3d.bj.bcebos.com/models/bevformer/bevformer_tiny_r50_fpn_nuscenes/model.pdparams`

**Comment by FlyingQianMM** [comment]
保存信息显示自定义算子没有运行成功：
![image](https://user-images.githubusercontent.com/22235422/224885303-73278e32-cd16-4332-a953-1f7db1b749e4.png)
![image](https://user-images.githubusercontent.com/22235422/224885325-436af58f-bf45-476f-93a7-bc6af399aebe.png)
确认下上面两个路径是否存在，另外使用GPU环境。

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
