### ISSUE TITLE
pointpilliars c++推理时报错：./build/main: error while loading shared libraries: libonnxruntime.so.1.11.1

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/Paddle3D#267]
在complish.sh 文件中设置了paddle_inference文件的路径为：LIB_DIR=/home/les/MyCode/Paddle3D/paddle_inference
执行 sh complish.sh 成功，但是运行可执行文件时报错为：
./build/main: error while loading shared libraries: libonnxruntime.so.1.11.1: cannot open shared object file: No such file or directory

查看了paddle_inference文件夹下third_party/install/onnxruntime/lib/路径下有libonnxruntime.so.1.11.1文件，但代码运行却找不到，请问这个怎么解决？

**Comment by wayyeah** [comment]
同样遇到这个问题，请问解决了吗

**Comment by cxy86121** [comment]
还没有解决掉🙃



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wayyeah ***@***.***&gt;
发送时间: 2023年3月19日 23:39
收件人: PaddlePaddle/Paddle3D ***@***.***&gt;
抄送: cxy86121 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/Paddle3D] pointpilliars c++推理时报错：./build/main: error while loading shared libraries: libonnxruntime.so.1.11.1 (Issue #267)





 
同样遇到这个问题，请问解决了吗

**Comment by nepeplwu** [comment]
@cxy86121 @wayyeah 这种问题一般是因为LD_LIBRARY_PATH设置不正确导致，建议检查下该FLAG设置

**Comment by cxy86121** [comment]
> @cxy86121 @wayyeah 这种问题一般是因为LD_LIBRARY_PATH设置不正确导致，建议检查下该FLAG设置

您好，我的环境变量设置是这样的：
export LD_LIBRARY_PATH=/usr/local/TensorRT-7.0.0.11/lib:$LD_LIBRARY_APTH
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_APTH
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_APT
而paddle_inference文件夹的路径在：/home/les/MyCode/Paddle3D/paddle_inference
请问是不是要将paddle_inference文件夹的路径也添加在环境变量中？

**Comment by will-jl944** [comment]
> /home/les/MyCode/Paddle3D/paddle_inference

paddle_inference的版本是多少？是自己编译的还是从哪里下载的？

**Comment by wayyeah** [comment]
> 还没有解决掉🙃 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: wayyeah ***@***.***&gt; 发送时间: 2023年3月19日 23:39 收件人: PaddlePaddle/Paddle3D ***@***.***&gt; 抄送: cxy86121 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [PaddlePaddle/Paddle3D] pointpilliars c++推理时报错：./build/main: error while loading shared libraries: libonnxruntime.so.1.11.1 (Issue #267) 同样遇到这个问题，请问解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

最粗暴的解决办法，locate libonnxruntime.so.1.11.1，然后到找到的目录把文件复制到/cpp目录

**Comment by cxy86121** [comment]
> > /home/les/MyCode/Paddle3D/paddle_inference
> 
> paddle_inference的版本是多少？是自己编译的还是从哪里下载的？

是在：https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html#c 下载的 manylinux_cuda10.2_cudnn7.6_avx_mkl_trt6_gcc5.4版本

**Comment by cxy86121** [comment]
> > 还没有解决掉🙃 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: wayyeah _**@**_._**> 发送时间: 2023年3月19日 23:39 收件人: PaddlePaddle/Paddle3D _**@**_.**_> 抄送: cxy86121 _**@**_._**>, Author _**@**_.**_> 主题: Re: [PaddlePaddle/Paddle3D] pointpilliars c++推理时报错：./build/main: error while loading shared libraries: libonnxruntime.so.1.11.1 (Issue #267) 同样遇到这个问题，请问解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 最粗暴的解决办法，locate libonnxruntime.so.1.11.1，然后到找到的目录把文件复制到/cpp目录

好滴，我试试看，谢谢~

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有需要请重新打开或者发起新的issue

**Comment by dongdongzi** [comment]
我也遇到了这个问题，在/etc/ld.so.conf添加了环境变量解决了
