### ISSUE TITLE
训练模型时报错

### ISSUE THREAD

**Issue by cherishTMYY** [PaddlePaddle/Paddle3D#275]
使用的指令：
python -m paddle.distributed.launch --gpus 0 tools/train.py --config configs/centerpoint/centerpoint_pillars_016voxel_kitti_mini.yml --num_workers 0 --log_interval 50 --save_interval 4 --save_dir output_centerpoint_kitti

报错的内容如下：
W0318 06:39:59.620198  1802 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 10.2
W0318 06:39:59.620215  1802 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
2023-03-18 06:40:00,309 -     INFO - Finish CenterHead Initialization
Traceback (most recent call last):
  File "tools/train.py", line 218, in <module>
    main(args)
  File "tools/train.py", line 212, in main
    trainer = Trainer(**dic)
TypeError: __init__() got an unexpected keyword argument 'do_bind'
LAUNCH INFO 2023-03-18 06:40:01,486 Exit code 1

**Comment by LielinJiang** [comment]
应该是你安装的paddle3d是旧版本的，但是train.py的代码是新版本的，你可以pip list看一下paddle3d的版本
修复的方法是clone develop的paddle3d，然后python setup.py develop进行安装。

**Comment by cherishTMYY** [comment]
> 应该是你安装的paddle3d是旧版本的，但是train.py的代码是新版本的，你可以pip list看一下paddle3d的版本 修复的方法是clone develop的paddle3d，然后python setup.py develop进行安装。

好的，非常感谢，我尝试一下您说的方法，我是直接将do_bind从train.py中注释掉了，再执行没有报错
