### ISSUE TITLE
使用飞桨的容器进行CenterPoint模型训练，并将其部署在apollo中，启动用是出现aborted的情况，请问是什么原因导致的

### ISSUE THREAD

**Issue by cherishTMYY** [PaddlePaddle/Paddle3D#276]
训练容器信息：
paddle:2.4.1-gpu-cuda10.2-cudnn7.6-trt7.0
下载的最新的Paddle3D 的代码

错误描述：
--- Running analysis [ir_graph_to_program_pass]
I0320 15:48:59.317131 17084 analysis_predictor.cc:1318] ======= optimize end =======
I0320 15:48:59.318094 17084 naive_executor.cc:110] --- skip [feed], feed -> data
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
what(): (NotFound) Operator (hard_voxelize) is not registered.
[Hint: op_info_ptr should not be null.] (at /apollo/data/Paddle/paddle/fluid/framework/op_info.h:156)

Aborted (core dumped)

**Comment by justld** [comment]
你好，请确认算子hard_voxelize相关配置正确

**Comment by cherishTMYY** [comment]
您好，请问这个hard_voxelize的配置是在什么文件中，刚接触这个东西

**Comment by cherishTMYY** [comment]
> 你好，请确认算子hard_voxelize相关配置正确

您好，请问这个hard_voxelize的配置是在什么文件中，刚接触这个东西

**Comment by justld** [comment]
参考：https://github.com/PaddlePaddle/Paddle3D/tree/develop/deploy/centerpoint/cpp/custom_ops

**Comment by wayyeah** [comment]
> 参考：https://github.com/PaddlePaddle/Paddle3D/tree/develop/deploy/centerpoint/cpp/custom_ops

@justld  你好，我同样遇到了这个问题，我在AI studio线上平台能够编译并运行，但在jetson 平台上编译完成后运行提示Operator (hard_voxelize) is not registered.，相关.cc .cu文件存在，请问要如何解决？

**Comment by nepeplwu** [comment]
@wayyeah 你的运行命令是？

**Comment by wayyeah** [comment]
> @wayyeah 你的运行命令是？

@nepeplwu 问题排查完了，是编译完的自定义算子的动态库没有链接上，要使用dlfcn 库手动链接上

**Comment by chenjian88888** [comment]
> > @wayyeah 你的运行命令是？
> 
> @nepeplwu 问题排查完了，是编译完的自定义算子的动态库没有链接上，要使用dlfcn 库手动链接上

请问怎么手动链接，自定义算字库编译了，target_link_libraries没用，dlopen("libpd_infer_custom_op.so", RTLD_GLOBAL);也还是出问题

**Comment by wayyeah** [comment]
@chenjian88888 

```
void *handle = dlopen("xxxx/libpd_infer_custom_op.so", RTLD_NOW);
if (!handle) {
        fprintf(stderr, "%s\n", dlerror());
        exit(EXIT_FAILURE);
    }
```
我用的这个代码，你可以试试

**Comment by chenjian88888** [comment]
> @chenjian88888
> 
> ```
> void *handle = dlopen("xxxx/libpd_infer_custom_op.so", RTLD_NOW);
> if (!handle) {
>         fprintf(stderr, "%s\n", dlerror());
>         exit(EXIT_FAILURE);
>     }
> ```
> 
> 我用的这个代码，你可以试试

哈哈，真的可以了，谢谢
