### ISSUE TITLE
voxel-rcnn模型export时报错

### ISSUE THREAD

**Issue by wcwc12-code** [PaddlePaddle/Paddle3D#280]
线上环境paddlepaddle2.4.0，paddle3d1.0导出训练好的voxel-rcnn模型时报如下错误
![问答](https://user-images.githubusercontent.com/74854487/227726560-b98b581c-7d28-410a-bfe1-6ff4ba4f5185.png)

**Comment by nepeplwu** [comment]
@wcwc12-code 我们已经修复该问题，可以先拉取PR验证下：https://github.com/PaddlePaddle/Paddle3D/pull/282

**Comment by Whwangluodan** [comment]
修复后已可以导出
