### ISSUE TITLE
KITTI数据和自己采集的数据处理相关问题

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/Paddle3D#284]
有两个问题想请教一下：
1.在训练3D点云目标检测模型时，如KITTI数据集中的样本按照难易程度分为了三类：easy、moderate和hard。这种分类会影响模型训练时损失计算和参数调整吗？
2.在自己采集的点云数据中，由于没有采集图像，直接标注的3D信息，这种情况下如何计算目标的截断占比？（看到源码中数据的难易值和截断信息、遮挡状态等有关）

**Comment by nepeplwu** [comment]
@cxy86121 
1. 这几个类别只是最终计算指标时区分了不同的样本计算mAP，不会影响loss
2. 建议上KITTI官网查看下说明

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
