### ISSUE TITLE
voxel-rcnn推理时报错

### ISSUE THREAD

**Issue by wcwc12-code** [PaddlePaddle/Paddle3D#285]
使用infer.py进行推理时报如下错误
![推理1](https://user-images.githubusercontent.com/74854487/228181172-6befb6f5-d3a3-4cb6-9f2f-775d80f1407c.png)
将infer.py中unused部分注释（如下）
![infer](https://user-images.githubusercontent.com/74854487/228181578-aa7d8608-f788-45b1-b5f7-8aa073c278e8.png)
则报如下错误
![推理2](https://user-images.githubusercontent.com/74854487/228181691-7f08cec4-29b0-4728-ac58-9dcc55eb8f57.png)

**Comment by wayyeah** [comment]
同样报No module named “pointnet2_ops"的错误，请问解决了吗？

**Comment by nepeplwu** [comment]
@wayyeah 感谢反馈，已经提交PR修复：https://github.com/PaddlePaddle/Paddle3D/pull/298。可以拉取该PR验证下

**Comment by wayyeah** [comment]
> @wayyeah 感谢反馈，已经提交PR修复：[https://github.com/PaddlePaddle/Paddle3D/pull/298。可以拉取该PR验证下](https://github.com/PaddlePaddle/Paddle3D/pull/298%E3%80%82%E5%8F%AF%E4%BB%A5%E6%8B%89%E5%8F%96%E8%AF%A5PR%E9%AA%8C%E8%AF%81%E4%B8%8B)

感谢修复，可以运行了
