### ISSUE TITLE
预测结果坐标相关问题

### ISSUE THREAD

**Issue by wcwc12-code** [PaddlePaddle/Paddle3D#312]
将pointpillars训练结果infer得到的Box(x_c, y_c, z_c, w, l, h, -rot)与kitti下txt label的第9~15位真值一一对应后相对比，发现相差很大。
请问预测结果如何转换为kitti格式的坐标。

**Comment by wcwc12-code** [comment]
主要是x_c,y_c,z_c坐标与kitti的label的xyz坐标相差较大,如以下两图是label和预测结果的可视化对比
![ZUAH5O IO)2QCJ}T7`%MG`4](https://user-images.githubusercontent.com/74854487/231919427-0f7bd625-ba60-4bb4-a668-6244e9a9b377.png)
![HQFZ8 (I_5W} 70T Q5L)5](https://user-images.githubusercontent.com/74854487/231919519-a08ed317-683b-478c-abad-bc3bd6ff6f74.png)

**Comment by cxy86121** [comment]
txt 文件中的label是图像坐标系下的，pointpillars训练结果infer得到的结果是点云坐标系下的，预测结果转为kitti标注文件格式坐标需要使用calib文件信息进行点云到图像坐标系的转换，相关代码在paddle3d/datasets/kitti/kitti_utils.py中可以参考。但如果你是想要可视化检测结果，没必要转换，可以参考代码https://github.com/PaddlePaddle/Paddle3D/issues/199，做简单修改后直接可视化。
