### ISSUE TITLE
pointpilliars模型配置文件中几个参数的相关问题

### ISSUE THREAD

**Issue by cxy86121** [PaddlePaddle/Paddle3D#315]
请问：
1.pointpilliars模型中配置文件的anchor_offsets参数是如何计算的；
2.train 、val以及export 时的max_voxel_num 不同，分别是根据什么得到的；
3.使用自己采集的数据集，没有对应的图片，生成真值库时可视化看了一下，发现好像每个类别打的标签，z方向的下半部分被截掉了，比如车子，只有车的上半部分，下半部分没有了，可视化打标的标签是正常的，使用KITTI数据集生成的真值库可视化出来也是正常的。请问在生成真值库的时候有没有设置默认的区域？在代码里没有找到.....
4.point_cloud_range是可以改动的吗？比如说我的检测场景中需要x(0,200),y(-100,100),z(-5,5),直接使用这样的范围有没有其他问题，试了一下，现存够的情况下直接这样设置好像有问题，跑的时候会报错。
5.还想问一下有没有关于配置文件的详解？

**Comment by will-jl944** [comment]
我们提供的PointPillars模型配置文件中，给定的点云单位（`point_cloud_range`）为`[ 0, -19.84, -2.5, 47.36, 19.84, 0.5 ]`，该范围够成了一个长宽高分别为47.36(m)、39.68(m)、3(m)的空间立方体。

给定的体素尺寸（`voxel_size`）为`[ 0.16, 0.16, 3 ]`，因此上述空间立方体会被切割成`47.36/0.16 * 39.68/0.16 * 3/3`=`296 * 248 * 1`个体素（原文中称pillars）。

每一个体素（pillars）的中心坐标点即为每一个anchor的位置。综合上述推导，每个体素（pillars）中心点在实际空间立方体中的坐标位置可以表示为：
- x轴：`[0.0 * 0.16(m) + anchor_offset_x(m), 1.0 * 0.16(m) + anchor_offset_x(m), ..., 295 * 0.16(m) + anchor_offset_x(m)]` = `[0.08(m), 0.24(m), ..., 47.28(m)]`，解得`anchor_offset_x = 0.08(m)`
- y轴：`[0.0 * 0.16(m) + anchor_offset_y(m), 1.0 * 0.16(m) + anchor_offset_y(m), ..., 295 * 0.16(m) + anchor_offset_y(m)]` = `[-19.76(m), -19.6(m), ..., 19.76(m)]`，解得`anchor_offset_x = -19.76(m)`
- z轴：同理，略
