### ISSUE TITLE
Caddn 推理错误，OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.

### ISSUE THREAD

**Issue by renli0810** [PaddlePaddle/Paddle3D#322]
Cuda 11.6
Cuddn 8.4.1
Python 3.8.16
PaddlePaddle 2.4.2
Ubuntu 20.04

在使用python进行部署时，出现如下错误，模型是官方提供的caddn_deeplabv3p_resnet101_os8_kitti

(paddle_env) renli@Renli:~/Paddle3D/deploy/caddn/python$ python infer.py --model_file ~/Paddle3D/caddn.pdmodel --params_file ~/Paddle3D/caddn.pdiparams --img_path ~/Paddle3D/000031.png
2023-05-01 11:00:34,210 -  WARNING - No custom op iou3d_nms_cuda found, try JIT build
Compiling user custom op, it will cost a few seconds.....
2023-05-01 11:00:35,570 -     INFO - iou3d_nms_cuda builded success!
Traceback (most recent call last):
  File "infer.py", line 196, in <module>
    main(args)
  File "infer.py", line 190, in main
    result = run(predictor, image)
  File "infer.py", line 168, in run
    predictor.run()
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/fluid/operators/grid_sampler_cudnn_op.cu.cc:81)
  [operator < grid_sampler > error]

**Comment by renli0810** [comment]
换成Cuda 11.2 Cudnn8.1.1 Python 3.8.16 PaddlePaddle 2.4.2 Ubuntu 18.04之后仍然存在这个问题

**Comment by wangna11BD** [comment]
官方提供的caddn_deeplabv3p_resnet101_os8_kitti是之前使用自定义算子grid_sampler导出的，推理时需要编译算子并import。目前新的代码已经改成使用paddle自带的grid_sampler了，官网模型未更新，我们会尽快更新的，感谢反馈。
您可以选择以下3种处理方式：1 版本回退到自定义算子grid_sampler删除前；2 使用最新的代码，自己导出模型；3 等待我们更新官网模型

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
