### ISSUE TITLE
关于训练CaDDN模型，准备数据集时的kitti_infos_train.pkl文件如何生成？

### ISSUE THREAD

**Issue by lixin010** [PaddlePaddle/Paddle3D#36]
准备数据集时的kitti_infos_train.pkl文件如何生成？

**Comment by wangna11BD** [comment]
目前代码还在修改中，可以先用这个
[kitti_infos.zip](https://github.com/PaddlePaddle/Paddle3D/files/9356172/kitti_infos.zip)

**Comment by lixin010** [comment]
> 目前代码还在修改中，可以先用这个 [kitti_infos.zip](https://github.com/PaddlePaddle/Paddle3D/files/9356172/kitti_infos.zip)

非常感谢你的回答，只是我需要在自己的数据集上来生成这个文件，请问[tool/create_det_gt_database.py](https://github.com/PaddlePaddle/Paddle3D/blob/develop/tools/create_det_gt_database.py)代码是用来生成这个pkl信息文件的吗

**Comment by wangna11BD** [comment]
tool/create_det_gt_database.py目前还不支持生成caddn的info，我们正在补充相关功能～

**Comment by weihongwei-zg** [comment]
请问如果要跑cadnn，必须要有点云数据吗？

**Comment by wangna11BD** [comment]
> > 目前代码还在修改中，可以先用这个 [kitti_infos.zip](https://github.com/PaddlePaddle/Paddle3D/files/9356172/kitti_infos.zip)
> 
> 非常感谢你的回答，只是我需要在自己的数据集上来生成这个文件，请问[tool/create_det_gt_database.py](https://github.com/PaddlePaddle/Paddle3D/blob/develop/tools/create_det_gt_database.py)代码是用来生成这个pkl信息文件的吗

kitti_infos_train.pkl可以使用tools/creat_caddn_kitti_infos.py来生成了～如果要用自己的数据生成，需要根据自己的数据集略微修改一下～

**Comment by wangna11BD** [comment]
> 请问如果要跑cadnn，必须要有点云数据吗？

需要点云数据的一些信息生成.pkl文件，如果直接从这里[kitti_infos.zip](https://github.com/PaddlePaddle/Paddle3D/files/9356172/kitti_infos.zip)下载.pkl文件，可以不用有点云数据
