### ISSUE TITLE
smoke输出结果有问题 

### ISSUE THREAD

**Issue by Ywenjun123** [PaddlePaddle/Paddle3D#383]
第10和11的数据太大了
[['Car' '0.0' '0' '1.8225346' '387.08566' '181.06418' '420.21432'
  '201.74832' '1.5236645' '1.7018363' '4.3047314' '16331608.0'
  '7711115.0' '55.71019' '-2.8898528' '0.782194']]

**Comment by perfectworld0415** [comment]
smoke.pdiparams  请问这个文件是在哪里下载的？我在model 中 只能下载到model.pdparams 这个文件

**Comment by Ywenjun123** [comment]
> smoke.pdiparams 请问这个文件是在哪里下载的？我在model 中 只能下载到model.pdparams 这个文件

那不就是一个吗

**Comment by perfectworld0415** [comment]
> 



> > smoke.pdiparams 请问这个文件是在哪里下载的？我在model 中 只能下载到model.pdparams 这个文件
> 


> > smoke.pdiparams 请问这个文件是在哪里下载的？我在model 中 只能下载到model.pdparams 这个文件
> 
> 那不就是一个吗

仔细看两个文件后缀是不一样的啊。ReadMe中提供的测试用的是两个文件。一个是smoke.pdmode  另一个是smoke.pdiparams， 而在model中只能下载到一个文件。
测试：python infer.py --model_file /path/to/smoke.pdmodel --params_file /path/to/smoke.pdiparams --image /path/to/image

**Comment by Ywenjun123** [comment]
使用如下命令导出训练完成的模型

# 导出Paddle3D提供的预训练模型
python tools/export.py --config configs/smoke/smoke_dla34_no_dcn_kitti.yml --model output/iter_70000/model.pdparams

**Comment by Ywenjun123** [comment]
> > 
> 
> > > smoke.pdiparams 请问这个文件是在哪里下载的？我在model 中 只能下载到model.pdparams 这个文件
> 
> > > smoke.pdiparams 请问这个文件是在哪里下载的？我在model 中 只能下载到model.pdparams 这个文件
> > 
> > 
> > 那不就是一个吗
> 
> 仔细看两个文件后缀是不一样的啊。ReadMe中提供的测试用的是两个文件。一个是smoke.pdmode 另一个是smoke.pdiparams， 而在model中只能下载到一个文件。 测试：python infer.py --model_file /path/to/smoke.pdmodel --params_file /path/to/smoke.pdiparams --image /path/to/image


就是一个，自己转换下，使用如下命令导出训练完成的模型
# 导出Paddle3D提供的预训练模型
python tools/export.py --config configs/smoke/smoke_dla34_no_dcn_kitti.yml --model output/iter_70000/model.pdparams
