### ISSUE TITLE
centerpoint是否支持fp16的QAT训练？

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle3D#385]
centerpoint是否支持fp16的QAT训练？

**Comment by will-jl944** [comment]
支持fp16 amp训练，参考配置文件：https://github.com/PaddlePaddle/Paddle3D/blob/develop/configs/centerpoint/centerpoint_pillars_02voxel_nuscenes_10sweep_ampO2_ultra.yml#L5

暂未支持int8 qat量化。
