### ISSUE TITLE
如何参与本项目开发

### ISSUE THREAD

**Issue by OuyangJunyuan** [PaddlePaddle/Paddle3D#39]
可以向仓库提交代码吗

**Comment by will-jl944** [comment]
Paddle3D为开源项目，欢迎提出建议和提交Pull Requests。

您如果方便的话，可以扫码加入Paddle3D的用户交流群，与我们核心研发工程师一起交流：

<div align="center">
<img src="https://user-images.githubusercontent.com/68210528/184829471-dff7740f-1c5c-4b93-ac7f-3c7f21179a43.jpg"  width = "300" />  
</div>
