### ISSUE TITLE
加载模型 RuntimeError: The specified component was not found  

### ISSUE THREAD

**Issue by Ywenjun123** [PaddlePaddle/Paddle3D#394]
训练时写在paddle3d文件写的模型注册后，加载不到。
自己写的测试脚本可以加载到。

**Comment by will-jl944** [comment]
请确认有在对应的`__init__.py`文件中import你自定义的模块，例如在`paddle3d/mdoels/detection`下自定义了模块并且使用`manager.xxx.add_component`注册后，需要在`paddle3d/mdoels/detection/__init__.py`中进行import。

如果问题仍未解决，请提供代码便于我们帮助你定位问题。
