### ISSUE TITLE
paddle3d上pointpillars结果比原论文高出很多，有针对改进发表的论文吗？我需要引用一下

### ISSUE THREAD

**Issue by NyquistBodeTu** [PaddlePaddle/Paddle3D#405]

**Comment by will-jl944** [comment]
论文中给出的是在KITTI test上面的指标，我们提供的是在KITTI val上面的指标，所以不同。

**Comment by NyquistBodeTu** [comment]
如果我想改进算法跑test来和别的算法比较mAP，但是test也没有label文件，这该怎么办呢？




D.Onlyone
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月18日(星期四) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle3D] paddle3d上pointpillars结果比原论文高出很多，有针对改进发表的论文吗？我需要引用一下 (Issue #405)





 
论文中给出的是在KITTI test上面的指标，我们提供的是在KITTI val上面的指标，所以不同。

**Comment by will-jl944** [comment]
需要将模型预测结果提交至KITTI数据集官网。

请参考KITTI提供的提交说明：https://www.cvlibs.net/datasets/kitti/user_submit.php
