### ISSUE TITLE
smoke测试报错

### ISSUE THREAD

**Issue by sumenpuyuan** [PaddlePaddle/Paddle3D#41]
定位到smoke_coder.py

![image](https://user-images.githubusercontent.com/14249563/184873084-c7a28818-41de-42f4-9fc1-4632a8605b0a.png)

矩阵求逆报错

![image](https://user-images.githubusercontent.com/14249563/184873183-7bd74d38-8a33-4e80-87f5-5926c52b63f5.png)

**Comment by nepeplwu** [comment]
@sumenpuyuan 你的执行命令是怎么样的呢？以及对应的paddle环境麻烦提供下

**Comment by sumenpuyuan** [comment]
命令：python tools/evaluate.py --config configs/smoke/smoke_dla34_no_dcn_kitti.yml --num_workers 2 --batch_size 1 --model checkpoints/model.pdparams
环境：paddle 2.3.1，python 3.7，cuda 10.2，cudnn 7.6

**Comment by nepeplwu** [comment]
@sumenpuyuan 麻烦执行下下面的代码，打印下更详细的环境信息发下
```python
import paddle3d.env as paddle3d_env
print(paddle3d_env.get_env_info())
```

**Comment by sumenpuyuan** [comment]
platform:
    Linux-4.15.0-142-generic-x86_64-with-debian-stretch-sid
    gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
    Python - 3.7.0 (default, Oct  9 2018, 10:31:47)  [GCC 7.3.0]

Science Toolkits:
    cv2 - 4.6.0
    numpy - 1.21.6
    numba - 0.56.0
    pandas - 1.1.5
    pillow - 9.2.0
    skimage - 0.19.3

PaddlePaddle:
    paddle(gpu) - 2.3.1
    paddle3d - 0.5.0
    paddleseg - 2.6.0
    FLAGS_cudnn_deterministic - Not set.
    FLAGS_cudnn_exhaustive_search - Not set.

CUDA:
    cudnn - 7603
    nvcc - Cuda compilation tools, release 10.2, V10.2.89

GPUs:
    GPU 0: TITAN Xp

**Comment by nepeplwu** [comment]
@sumenpuyuan 感谢反馈，我们使用了多个类似的环境（cudnn 7.6.5 + cuda10.2 + paddle2.3,1），均无法复现这个问题。
从报错日志来看，该问题并不是paddle框架自身抛出的异常（），一般这种问题都是环境配置问题，例如cudnn和cuda版本不匹配，或者安装的paddle版本和本地cuda版本不匹配导致，建议再验证下环境是否有问题，如果还是存在问题的话，建议使用docker来避免环境问题，推荐飞桨官方镜像：registry.baidubce.com/paddlepaddle/paddle:2.3.0-gpu-cuda10.2-cudnn7
