### ISSUE TITLE
是否有可视化代码，以及对应坐标系转换说明文档（例如smoke模型的，小白想学习一下）

### ISSUE THREAD

**Issue by weihongwei-zg** [PaddlePaddle/Paddle3D#42]
我使用的可视化代码：https://github.com/liyingying0113/rope3d-dataset-tools/tree/main/show_tools

**Comment by FlyingQianMM** [comment]
KITTI数据集的坐标系定义可以参考这个博客说明哈：https://towardsdatascience.com/kitti-coordinate-transformations-125094cd42fb

**Comment by 694376965** [comment]
@FlyingQianMM @wobushihuair 
哈喽大家好，请问可视化成功了吗？能否参考一下代码？非常感谢！

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
