### ISSUE TITLE
Paddle3D(SMOKE)如何使用自己的摄像头进行部署

### ISSUE THREAD

**Issue by LeungWaiHo** [PaddlePaddle/Paddle3D#420]
### Paddle3D(SMOKE)如何使用自己的摄像头进行部署

1、我使用的是Realsense相机，内参已改成Realsense相机的，请问还需要更改哪些参数，以实现物体的3D目标框检测以及3D目标框在2D图像上的投影；
2、我目前仅更改了相机内参矩阵[K](https://github.com/PaddlePaddle/Paddle3D/blob/dc031ec509fa1f16c6259de2b0ef975d88929013/deploy/smoke/python/infer.py#L144)，但似乎3D目标框的投影不太准确，如问题1所示，我还要更改哪些地方？

**Comment by FlyingQianMM** [comment]
1. 确认我们给的部署demo是可以正常运行的 https://github.com/PaddlePaddle/Paddle3D/tree/develop/configs/smoke#python%E9%83%A8%E7%BD%B2
2. 目前Smoke预测的结果是相机坐标系下的，投影到图像可视化只需要相机内参矩阵即可。如果怀疑是内参矩阵给的不对，可以把部署demo里预测的部分注释掉，就直接给定一个确定的三维点，只跑投影的代码，看可视化结果是否正确，在debug
3. 如果预测效果不是很好，建议在自己的数据集上再finetune下，smoke只用图像的话本身精度不是很高

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
