### ISSUE TITLE
请问paddle使用的libstdc++.so.6是ubuntu系统环境中的还是conda环境中的？

### ISSUE THREAD

**Issue by wuba-pat** [PaddlePaddle/Paddle3D#433]
Ubuntu系统中的libstdc++.so.6是6.0.28版本的。
因此当我在paddle_env下import paddle时 一直在报错 ImportError: libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/funnywii/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/base/libpaddle.so)

后来我发现~/.conda/envs/paddle_env/lib 中有一个libstdc++.so.6.0.32，我不确定是不是在conda install -c conda-forge gcc=12.2.0之后才出现的这个库。

当我将终端的目录cd至~/.conda/envs/paddle_env/lib以后，这个问题就消失了。

所以paddle使用的libstdc++.so.6是ubuntu系统环境中的还是conda环境中的？

**Comment by warrentdrew** [comment]
可以ldd /home/funnywii/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/base/libpaddle.so 看下libstdc++.so.6这个依赖库的位置

**Comment by wuba-pat** [comment]
> 可以ldd /home/funnywii/.conda/envs/paddle_env/lib/python3.8/site-packages/paddle/base/libpaddle.so 看下libstdc++.so.6这个依赖库的位置

结果如下，这个问题已经通过更新libstdc++到6.0.32解决了。

linux-vdso.so.1 (0x00007ffc7c5c5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feb31406000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007feb313fc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007feb313e0000)
	libphi.so => /home/funnywii/.conda/envs/paddle/lib/python3.8/site-packages/paddle/base/./../libs/libphi.so (0x00007feab89ab000)
	libcommon.so => /home/funnywii/.conda/envs/paddle/lib/python3.8/site-packages/paddle/base/./../libs/libcommon.so (0x00007feab879d000)
	libdnnl.so.3 => /home/funnywii/.conda/envs/paddle/lib/python3.8/site-packages/paddle/base/./../libs/libdnnl.so.3 (0x00007feab5a24000)
	libiomp5.so => /home/funnywii/.conda/envs/paddle/lib/python3.8/site-packages/paddle/base/./../libs/libiomp5.so (0x00007feab562f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feab5629000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feab53bb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feab526c000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007feab521b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feab51f4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feab5002000)
	/lib64/ld-linux-x86-64.so.2 (0x00007feb4e14f000)


能麻烦您看一下 #436 这个问题吗
