### ISSUE TITLE
请问pointpillars的infer.py推理完成后的结果是什么意思呢，可以说明下吗

### ISSUE THREAD

**Issue by jasper-cell** [PaddlePaddle/Paddle3D#435]
![image](https://github.com/PaddlePaddle/Paddle3D/assets/54393886/5f8c3f56-8d91-4b1c-9ef2-6dbc4513fd4c)

**Comment by will-jl944** [comment]
`Score`: 检测结果置信度
`Label`: 检测结果类别标签
`Box(x_c, y_c, z_c, w, l, h, -rot)`: 检测结果bounding box信息，包含7个数值吗，按照顺序依次为中心点x轴坐标、中心点y轴坐标、中心点z轴坐标、宽度、长度、高度、偏航角（弧度制）。
