### ISSUE TITLE
Paddle3D 1.1版本安装报错

### ISSUE THREAD

**Issue by Lucas-SJY** [PaddlePaddle/Paddle3D#449]
在按照文档安装运行pip install -e .时，发生如下报错
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/lucas/Documents/kittifull/Paddle3D-release-1.1
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/setup.py", line 20, in <module>
          import paddle3d
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/__init__.py", line 28, in <module>
          from . import datasets, models, transforms
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/datasets/__init__.py", line 16, in <module>
          from .kitti import KittiDepthDataset, KittiMonoDataset, KittiPCDataset
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/datasets/kitti/__init__.py", line 15, in <module>
          from .kitti_depth_det import KittiDepthDataset
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/datasets/kitti/kitti_depth_det.py", line 26, in <module>
          import paddle3d.transforms as T
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/transforms/__init__.py", line 15, in <module>
          from paddle3d.transforms.anchor_generator import *
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/transforms/anchor_generator.py", line 21, in <module>
          from paddle3d.apis import manager
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/apis/__init__.py", line 16, in <module>
          from .config import Config
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/apis/config.py", line 24, in <module>
          from paddle3d.utils.tensor_fusion_utils import (fused_parameters,
        File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/utils/tensor_fusion_utils.py", line 19, in <module>
          from paddle.fluid.framework import EagerParamBase
      ModuleNotFoundError: No module named 'paddle.fluid'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

系统是Ubuntu22.04, Paddle版本是2.6.0

**Comment by will-jl944** [comment]
> ModuleNotFoundError: No module named 'paddle.fluid'

Paddle v2.6.0中移除了`fluid`模块，Paddle3D暂未进行适配。可以使用Paddle v2.5.x进行安装。

**Comment by Lucas-SJY** [comment]
我已经切换成paddle2.5.2， 在使用python tools/train.py --config configs/centerpoint/centerpoint_pillars_016voxel_kitti.yml --save_dir ./output_kitti_centerpoint --save_interval 5 --log_interval 5命令训练时， 报错
2024-02-19 15:27:17,255 -  WARNING - No custom op voxelize found, try JIT build
Compiling user custom op, it will cost a few seconds.....
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/lib/gcc/x86_64-linux-gnu/11/include/serializeintrin.h(41): error: identifier "__builtin_ia32_serialize" is undefined

1 error detected in the compilation of "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu".
error: command '/usr/bin/nvcc' failed with exit code 1
2024-02-19 15:27:22,562 -    ERROR - voxelize builded fail!
Traceback (most recent call last):
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/__init__.py", line 168, in _load_module
    self.module = importlib.import_module(self.modulename)
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'voxelize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1378, in run_cmd
    return subprocess.check_call(command, shell=True, stdout=DEVNULL)
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/lucas/.cache/paddle_extensions && /home/lucas/.conda/envs/paddle/bin/python voxelize_setup.py build' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 265, in <module>
    main(args)
  File "tools/train.py", line 260, in main
    trainer.train()
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/apis/trainer.py", line 353, in train
    output = training_step(
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/apis/pipeline.py", line 87, in training_step
    outputs = model(sample)
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/models/base/base_model.py", line 70, in forward
    return self.train_forward(samples, *args, **kwargs)
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/models/detection/centerpoint/centerpoint.py", line 150, in train_forward
    x = self.extract_feat(data)
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/models/detection/centerpoint/centerpoint.py", line 127, in extract_feat
    voxels, coordinates, num_points_in_voxel = self.voxelizer(
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/models/voxelizers/voxelize.py", line 69, in forward
    voxels, coors_pad, num_points_per_voxel = self.single_forward(
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/models/voxelizers/voxelize.py", line 40, in single_forward
    voxels, coors, num_points_per_voxel, voxels_num = voxelize.hard_voxelize(
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/__init__.py", line 186, in __getattr__
    module = self._load_module()
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/__init__.py", line 172, in _load_module
    self.module = self.jit_build()
  File "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/__init__.py", line 159, in jit_build
    return paddle_jit_load(
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/cpp_extension.py", line 944, in load
    _jit_compile(file_path, verbose)
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1339, in _jit_compile
    run_cmd(compile_cmd, verbose)
  File "/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/utils/cpp_extension/extension_utils.py", line 1381, in run_cmd
    raise RuntimeError(f"Failed to run command: {compile}, errors: {error}")
RuntimeError: Failed to run command: <built-in function compile>, errors: Command 'cd /home/lucas/.cache/paddle_extensions && /home/lucas/.conda/envs/paddle/bin/python voxelize_setup.py build' returned non-zero exit status 1.

于是单独运行/home/lucas/.conda/envs/paddle/bin/python voxelize_setup.py build

发生如下报错

running build
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'voxelize' extension
gcc -pthread -B /home/lucas/.conda/envs/paddle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cc -o /home/lucas/.cache/paddle_extensions/voxelize/voxelize_op.o -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/bin/nvcc -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu -o /home/lucas/.cache/paddle_extensions/voxelize/voxelize_op.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
/usr/lib/gcc/x86_64-linux-gnu/11/include/serializeintrin.h(41): error: identifier "__builtin_ia32_serialize" is undefined

1 error detected in the compilation of "/home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu".
error: command '/usr/bin/nvcc' failed with exit code 1

我的gcc g++版本为11.4 ncvvv版本为11.5.119

**Comment by will-jl944** [comment]
> 我的gcc g++版本为11.4

可能是gcc版本不匹配导致的，建议切换至v8.x（例如v8.2）。

执行如下步骤进行验证：
```shell
cd /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/
python setup.py install
```

**Comment by Lucas-SJY** [comment]
我将gcc版本切换至了8.4.0 随后执行
`cd /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/
python setup.py install`
然后发生报错
`building 'voxelize' extension
gcc -pthread -B /home/lucas/.conda/envs/paddle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cc -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/bin/nvcc -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc: No such file or directory
nvcc fatal   : Failed to preprocess host compiler properties.`

我的nvcc版本是
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0`

**Comment by will-jl944** [comment]
> cc: No such file or directory

报错信息中是否有`No such file or directory`所指的具体路径？

**Comment by Lucas-SJY** [comment]
> 报错信息中是否有No such file or directory所指的具体路径？

这些是全部报错信息了

**Comment by Lucas-SJY** [comment]
> 报错信息中是否有No such file or directory所指的具体路径？
以下是运行python setup.py install的全部输出
`ortools not installed, install it by "pip install ortools==9.1.9490" if you run BEVLaneDet model
running install
/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing voxelize.egg-info/PKG-INFO
writing dependency_links to voxelize.egg-info/dependency_links.txt
writing top-level names to voxelize.egg-info/top_level.txt
reading manifest file 'voxelize.egg-info/SOURCES.txt'
writing manifest file 'voxelize.egg-info/SOURCES.txt'
installing library code to build/voxelize/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'voxelize' extension
gcc -pthread -B /home/lucas/.conda/envs/paddle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cc -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/bin/nvcc -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc: No such file or directory
nvcc fatal   : Failed to preprocess host compiler properties.
error: command '/usr/bin/nvcc' failed with exit code 1`

**Comment by will-jl944** [comment]
请粘贴下执行`python -c "import paddle;paddle.utils.run_check()"`的输出，看下CUDA是否配置正确。

**Comment by Lucas-SJY** [comment]
> CUDA是否配置正确。

以下是该代码的执行结果，CUDA配置正确
`(paddle) lucas@lucas-Laptop:~/.conda/envs/paddle/include$ python -c "import paddle;paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
I0220 15:11:27.151290  8240 interpretercore.cc:237] New Executor is Running.
W0220 15:11:27.151435  8240 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 11.6
W0220 15:11:27.153491  8240 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
I0220 15:11:29.604952  8240 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`

**Comment by will-jl944** [comment]
> Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 11.6

> 我的nvcc版本是
> `nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Thu_Nov_18_09:45:30_PST_2021 Cuda compilation tools, release 11.5, V11.5.119 Build cuda_11.5.r11.5/compiler.30672275_0`


这里显示CUDA版本是11.6，但是上面你用到的nvcc版本是11.5。你的nvcc是和CUDA一起安装的吗？本地是否同时存在多个CUDA版本？

**Comment by Lucas-SJY** [comment]
> 这里显示CUDA版本是11.6，但是上面你用到的nvcc版本是11.5

我在将nvcc版本切换至11.6 后，报错依旧
以下是我的nvcc 信息
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0`

报错也依然是
`ortools not installed, install it by "pip install ortools==9.1.9490" if you run BEVLaneDet model
running install
/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing voxelize.egg-info/PKG-INFO
writing dependency_links to voxelize.egg-info/dependency_links.txt
writing top-level names to voxelize.egg-info/top_level.txt
reading manifest file 'voxelize.egg-info/SOURCES.txt'
writing manifest file 'voxelize.egg-info/SOURCES.txt'
installing library code to build/voxelize/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'voxelize' extension
gcc -pthread -B /home/lucas/.conda/envs/paddle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cc -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-11.6/bin/nvcc -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc: No such file or directory
nvcc fatal   : Failed to preprocess host compiler properties.
error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1`

**Comment by will-jl944** [comment]
> 我将gcc版本切换至了8.4.0

替换的的gcc 8.4.0是否有软链至`/usr/bin/cc`?

**Comment by Lucas-SJY** [comment]
我已将gcc软链至 /usr/bin/cc
ls -l /usr/bin/cc显示
`gcc -> /bin/gcc`
同时我已经将nvcc加入环境变量

现在报错信息变为

`running bdist_egg
running egg_info
writing voxelize.egg-info/PKG-INFO
writing dependency_links to voxelize.egg-info/dependency_links.txt
writing top-level names to voxelize.egg-info/top_level.txt
reading manifest file 'voxelize.egg-info/SOURCES.txt'
writing manifest file 'voxelize.egg-info/SOURCES.txt'
installing library code to build/voxelize/bdist.linux-x86_64/egg
running install_lib
running build_ext
Compiling user custom op, it will cost a few seconds.....
building 'voxelize' extension
gcc -pthread -B /home/lucas/.conda/envs/paddle/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cc -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.o -DPADDLE_WITH_CUDA -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -DPADDLE_WITH_CUDA -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-11.6/bin/nvcc -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include -I/home/lucas/.conda/envs/paddle/lib/python3.8/site-packages/paddle/include/third_party -I/usr/local/cuda-11.6/include -I/home/lucas/.conda/envs/paddle/include/python3.8 -I/home/lucas/.conda/envs/paddle/include/python3.8 -c /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/voxel/voxelize_op.cu -o /home/lucas/Documents/kittifull/Paddle3D-release-1.1/paddle3d/ops/build/voxelize/lib.linux-x86_64-cpython-38/voxelize_op.cu.o -DPADDLE_WITH_CUDA -DEIGEN_USE_GPU -ccbin cc -Xcompiler -fPIC --expt-relaxed-constexpr -DNVCC -w -DPADDLE_WITH_CUSTOM_KERNEL -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
cc: Permission denied
nvcc fatal   : Failed to preprocess host compiler properties.
error: command '/usr/local/cuda-11.6/bin/nvcc' failed with exit code 1`

**Comment by will-jl944** [comment]
执行正确的话，`ls -l /usr/bin/cc`应该显示:
`/usr/bin/cc -> ${gcc路径}`

以及确认下软链后`/usr/bin/cc`的文件权限。
