### ISSUE TITLE
自制纯点云数据集检测mAP很低

### ISSUE THREAD

**Issue by NyquistBodeTu** [PaddlePaddle/Paddle3D#454]
您好，自制纯点云数据集大约500个样本，大约总共三千个目标，只有一类，使用pointpillars算法，训练160轮，AP值很低，只有20左右。请问正常吗？增加数据量会好一点吗？还是应该优化算法

**Comment by warrentdrew** [comment]
您好，因为样本比较少，可以观察下训练集和验证集是否精度差异比较大，如果差异较大可能是出现过拟合的情况，增加数据量会有帮助

**Comment by NyquistBodeTu** [comment]
> 您好，因为样本比较少，可以观察下训练集和验证集是否精度差异比较大，如果差异较大可能是出现过拟合的情况，增加数据量会有帮助

您好，我的训练集AP为18，测试集AP为10，虽然结果都很差，但应该也是过拟合的，后面准备再增加数据量。另外，想请教一下，我的激光是16线的，点数很少，减小网络宽度是否也能缓解过拟合？

**Comment by warrentdrew** [comment]
减小宽度可以减少网络参数量，对缓解过拟合也会有作用

**Comment by NyquistBodeTu** [comment]
> 减小宽度可以减少网络参数量，对缓解过拟合也会有作用
好的，感谢您的建议，我回头试一试
