### ISSUE TITLE
训练CaDDN模型时，编译grid_sample_3d算子失败！

### ISSUE THREAD

**Issue by lixin010** [PaddlePaddle/Paddle3D#48]
![966c2c95cf9b67ad2ce3631bedb3247](https://user-images.githubusercontent.com/34670271/185876243-9c0b8128-a04f-49fc-91ed-1fed1b199864.jpg)
在国产显卡DCU环境上训练CaDDN模型出现上图报错，查看了一下grid_sample_3d是cuda c写的算子，是因为DCU是ROCm框架，没有cuda环境，所以编译失败吗？
CaDDN是否支持在ROCm环境下进行训练呢？

**Comment by wangna11BD** [comment]
paddle3d中的grid_sample_3d是cuda c写的算子，暂时不支持ROCm框架。
目前develop版的paddle已经支持grid_sample_3d算子了，您可以安装develop版的paddle，删去paddle3d中自定义grid_sample_3d的代码，用paddle自带的grid_sample_3d试试看～

**Comment by sunhm15** [comment]
> paddle3d中的grid_sample_3d是cuda c写的算子，暂时不支持ROCm框架。 目前develop版的paddle已经支持grid_sample_3d算子了，您可以安装develop版的paddle，删去paddle3d中自定义grid_sample_3d的代码，用paddle自带的grid_sample_3d试试看～

您好，我在develop版本的api里没有中找到grid_sample_3d算子，能帮忙发现链接，学习下使用方法吗？

**Comment by wangna11BD** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/grid_sample_cn.html#canshu
develop版本的grid_sample支持5d输入，5d输入就是grid_sample_3d
