### ISSUE TITLE
custom kitti data question

### ISSUE THREAD

**Issue by Kerry678231** [PaddlePaddle/Paddle3D#50]
想请教一下，自己做kitti数据集，有什么开源好用的工具吗？

**Comment by Birdylx** [comment]
@Kerry678231 Hi，请参考[point-cloud-annotation-tool](https://github.com/springzfx/point-cloud-annotation-tool)，其支持KITTI-bin格式。

**Comment by Kerry678231** [comment]
非常感谢！！！

**Comment by devendraswamy** [comment]
@Kerry678231 Did you labelled and trained the model , If its done could you please transfer the KT here. Thanking you in advance.
