### ISSUE TITLE
nuscenes数据集转换成kitti格式

### ISSUE THREAD

**Issue by guohuanguohuan** [PaddlePaddle/Paddle3D#51]
你好，请问是否有nuscenes数据集转换成kitti格式的代码？

**Comment by Birdylx** [comment]
@helloyizhengjun Hi, Paddle3D当前支持nuScenes数据集，是可以直接使用的，为何有转换kitti的需求？

**Comment by guohuanguohuan** [comment]
主要是我想用这个功能😅，所以问问有没有😇😇



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月25日(周四) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle3D] nuscenes数据集转换成kitti格式 (Issue #51)




 
@helloyizhengjun Hi, Paddle3D当前支持nuScenes数据集，是可以直接使用的，为何有转换kitti的需求？

**Comment by PetraWang** [comment]
@helloyizhengjun Hi, 请问SMOKE也支持nuScenes数据集训练嘛

**Comment by guohuanguohuan** [comment]
> @helloyizhengjun Hi, 请问SMOKE也支持nuScenes数据集训练嘛

抱歉哈！这个我用的其实不多，我也不清楚。

**Comment by nepeplwu** [comment]
@PetraWang 目前没有适配nuScenes数据集，所以不支持

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
