### ISSUE TITLE
可以增加shapeNet数据集吗

### ISSUE THREAD

**Issue by Skye2099** [PaddlePaddle/Paddle3D#52]
可以增加shapeNet数据集吗

**Comment by Birdylx** [comment]
@Skye2099 当前Paddle3D主要聚焦于自动驾驶感知，目前不支持ShapNet数据集，我们会评估下是否加入。当然，你可以参考[这里](https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/datasets/semantic_kitti/semantic_kitti_seg.py)实现自定义的Dataset
