### ISSUE TITLE
readme demo so good for muli lidar  input ？

### ISSUE THREAD

**Issue by zyxcambridge** [PaddlePaddle/Paddle3D#54]

**Comment by zyxcambridge** [comment]
datasets is nuscens？or waymo？ model is  centerpoint？ train sets？  the result maybe fake ，better than gt

**Comment by Birdylx** [comment]
@zyxcambridge Hi, the demo gif is from waymo train set. We just simply draw the gt on point cloud & camera image, you can refer [here](https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_camera_only.ipynb) for visualization. It's just for a viz demo, so don't be confused about the result.

**Comment by zyxcambridge** [comment]
> 

so the result gif is from gt  not predict？

**Comment by Birdylx** [comment]
>  so the result gif is from gt not predict？

Exactly, it's just a gt visualization gif demo. We will add visualization capabilities in the future, please stay tuned.
