### ISSUE TITLE
python  python/infer.py --model_file   centerpoint.pdmodel --params_file   centerpoint.pdiparams   --lidar_file  /zyx/Paddle3D/n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603647672.pcd.bin    --num_point_dim 5

### ISSUE THREAD

**Issue by zyxcambridge** [PaddlePaddle/Paddle3D#55]
python  python/infer.py --model_file   centerpoint.pdmodel --params_file   centerpoint.pdiparams   --lidar_file    zyx/Paddle3D/n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603647672.pcd.bin    --num_point_dim 5
INFO 2022-08-25 20:34:23,899 utils.py:147] Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-08-25 20:34:24,657 -  WARNING - No custom op centerpoint_postprocess found, try JIT build
Compiling user custom op, it will cost a few seconds.....
2022-08-25 20:34:26,975 -     INFO - centerpoint_postprocess builded success!
2022-08-25 20:34:26,975 -  WARNING - No custom op voxelize found, try JIT build
Compiling user custom op, it will cost a few seconds.....
W0825 20:34:29.208118 20410 custom_operator.cc:698] Operator (centerpoint_postprocess) has been registered.
2022-08-25 20:34:29,231 -     INFO - voxelize builded success!
I0825 20:34:29.234148 20410 helper.cc:54] The operator `hard_voxelize` has been registered. Therefore, we will not repeat the registration here.
I0825 20:34:29.234172 20410 helper.cc:54] The operator `centerpoint_postprocess` has been registered. Therefore, we will not repeat the registration here.
W0825 20:34:32.965904 20410 analysis_predictor.cc:1086] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0825 20:34:33.183665 20410 fuse_pass_base.cc:57] ---  detected 18 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
I0825 20:34:33.244004 20410 fuse_pass_base.cc:57] ---  detected 37 subgraphs
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
I0825 20:34:33.255827 20410 fuse_pass_base.cc:57] ---  detected 2 subgraphs
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I0825 20:34:33.339251 20410 fuse_pass_base.cc:57] ---  detected 36 subgraphs
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0825 20:34:33.352551 20410 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0825 20:34:33.417654 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_125.tmp_1  size: 65536
I0825 20:34:33.417690 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_137.tmp_1  size: 65536
I0825 20:34:33.417697 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_173.tmp_1  size: 65536
I0825 20:34:33.417702 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_121.tmp_1  size: 65536
I0825 20:34:33.417708 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_161.tmp_1  size: 65536
I0825 20:34:33.417713 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_165.tmp_1  size: 131072
I0825 20:34:33.417718 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_133.tmp_1  size: 131072
I0825 20:34:33.417724 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_123.tmp_1  size: 131072
I0825 20:34:33.417730 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_179.tmp_1  size: 131072
I0825 20:34:33.417737 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_171.tmp_1  size: 131072
I0825 20:34:33.417742 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_119.tmp_1  size: 131072
I0825 20:34:33.417748 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_139.tmp_1  size: 196608
I0825 20:34:33.417754 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_175.tmp_1  size: 196608
I0825 20:34:33.417762 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_149.tmp_1  size: 65536
I0825 20:34:33.417768 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_115.tmp_1  size: 196608
I0825 20:34:33.417773 20410 memory_optimize_pass.cc:216] Cluster name : fill_constant_7.tmp_0  size: 67108864
I0825 20:34:33.417780 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_transpose_1.tmp_0  size: 8388608
I0825 20:34:33.417789 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_147.tmp_1  size: 131072
I0825 20:34:33.417798 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_177.tmp_1  size: 131072
I0825 20:34:33.417804 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_157.tmp_1  size: 65536
I0825 20:34:33.417810 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_141.tmp_1  size: 131072
I0825 20:34:33.417816 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_153.tmp_1  size: 131072
I0825 20:34:33.417822 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_111.tmp_1  size: 131072
I0825 20:34:33.417829 20410 memory_optimize_pass.cc:216] Cluster name : relu_2.tmp_0  size: 16777216
I0825 20:34:33.417834 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_145.tmp_1  size: 131072
I0825 20:34:33.417840 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_129.tmp_1  size: 131072
I0825 20:34:33.417845 20410 memory_optimize_pass.cc:216] Cluster name : relu_20.tmp_0  size: 8388608
I0825 20:34:33.417851 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_117.tmp_1  size: 131072
I0825 20:34:33.417857 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_131.tmp_1  size: 131072
I0825 20:34:33.417863 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_155.tmp_1  size: 131072
I0825 20:34:33.417869 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_143.tmp_1  size: 131072
I0825 20:34:33.417874 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_167.tmp_1  size: 131072
I0825 20:34:33.417881 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_113.tmp_1  size: 65536
I0825 20:34:33.417886 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_169.tmp_1  size: 131072
I0825 20:34:33.417892 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_135.tmp_1  size: 131072
I0825 20:34:33.417898 20410 memory_optimize_pass.cc:216] Cluster name : scatter_0.tmp_0  size: 67108864
I0825 20:34:33.417904 20410 memory_optimize_pass.cc:216] Cluster name : conv2d_159.tmp_1  size: 131072
--- Running analysis [ir_graph_to_program_pass]
I0825 20:34:33.530231 20410 analysis_predictor.cc:1007] ======= optimize end =======
I0825 20:34:33.534845 20410 naive_executor.cc:102] ---  skip [feed], feed -> data
I0825 20:34:33.538702 20410 naive_executor.cc:102] ---  skip [_generated_var_9], fetch -> fetch
I0825 20:34:33.538723 20410 naive_executor.cc:102] ---  skip [_generated_var_11], fetch -> fetch
I0825 20:34:33.538730 20410 naive_executor.cc:102] ---  skip [_generated_var_10], fetch -> fetch
W0825 20:34:33.540565 20410 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 10.2
W0825 20:34:33.562711 20410 gpu_context.cc:306] device: 0, cuDNN Version: 8.4.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1661430876 (unix time) try "date -d @1661430876" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 20410 (TID 0x7f0e2ecab0c0) from PID 0 ***]

**Comment by FlyingQianMM** [comment]
我这边用paddle 2.3.2或者2.3.1可以正常跑，检测nuscenes的lidar数据

```
python python/infer.py --model_file ../..//output_inference/centerpoint.pdmodel --params_file ../../output_inference/centerpoint.pdiparams --lidar_file ./n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603547590.pcd.bin --num_point_dim 5
```

想问下您使用的CUDA/cuDNN版本号，已经安装paddlepaddle_gpu版本号是多少？

**Comment by zyxcambridge** [comment]
cuda 11.1  ，cudnn 8.x

Package                       Version              Location
----------------------------- -------------------- ---------------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astor                         0.8.1
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bce-python-sdk                0.8.74
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bitarray                      2.4.1
bkcharts                      0.2
black                         19.10b0
bleach                        4.1.0
bokeh                         2.4.2
boto3                         1.21.32
botocore                      1.24.32
Bottleneck                    1.3.4
brotlipy                      0.7.0
cachetools                    4.2.2
certifi                       2021.10.8
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
clyent                        1.2.2
colorama                      0.4.4
colorcet                      2.0.6
colorlog                      6.6.0
conda                         4.12.0
conda-build                   3.21.8
conda-content-trust           0+unknown
conda-pack                    0.6.0
conda-package-handling        1.8.1
conda-repo-cli                1.0.4
conda-token                   0.3.0
conda-verify                  3.4.2
constantly                    15.1.0
cookiecutter                  1.7.3
cryptography                  3.4.8
cssselect                     1.1.0
cycler                        0.11.0
Cython                        0.29.28
cytoolz                       0.11.0
daal4py                       2021.5.0
dask                          2022.2.1
datashader                    0.13.0
datashape                     0.5.4
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
descartes                     1.1.0
diff-match-patch              20200713
distributed                   2022.2.1
docutils                      0.17.1
easydict                      1.9
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     0.8.3
fastjsonschema                2.15.1
filelock                      3.6.0
fire                          0.4.0
flake8                        3.9.2
Flask                         1.1.2
Flask-Babel                   2.0.0
fonttools                     4.25.0
frozenlist                    1.2.0
fsspec                        2022.2.0
future                        0.18.2
gensim                        4.1.2
glob2                         0.7
gmpy2                         2.1.2
google-api-core               1.25.1
google-auth                   1.33.0
google-cloud-core             1.7.1
google-cloud-storage          1.31.0
google-crc32c                 1.1.2
google-resumable-media        1.3.1
googleapis-common-protos      1.53.0
greenlet                      1.1.1
grpcio                        1.42.0
h5py                          3.6.0
HeapDict                      1.0.1
holoviews                     1.14.8
hvplot                        0.7.3
hyperlink                     21.0.0
idna                          3.3
imagecodecs                   2021.8.26
imageio                       2.9.0
imagesize                     1.3.0
importlib-metadata            4.11.3
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.5
intervaltree                  3.1.0
ipykernel                     6.9.1
ipython                       8.2.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isort                         5.9.3
itemadapter                   0.3.0
itemloaders                   1.0.4
itsdangerous                  2.0.1
jdcal                         1.4.1
jedi                          0.18.1
jeepney                       0.7.1
Jinja2                        2.11.3
jinja2-time                   0.2.0
jmespath                      0.10.0
joblib                        1.1.0
json5                         0.9.6
jsonschema                    4.4.0
jupyter                       1.0.0
jupyter-client                6.1.12
jupyter-console               6.4.0
jupyter-core                  4.9.2
jupyter-server                1.13.5
jupyterlab                    3.3.2
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.0
keyring                       23.4.0
kiwisolver                    1.3.2
lap                           0.4.0
lazy-object-proxy             1.6.0
libarchive-c                  2.9
llvmlite                      0.38.0
locket                        0.2.1
lxml                          4.8.0
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.5.1
matplotlib-inline             0.1.2
mccabe                        0.6.1
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mock                          4.0.3
motmetrics                    1.2.5
mpmath                        1.2.1
msgpack                       1.0.2
multidict                     5.2.0
multipledispatch              0.6.0
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.2.1
nbclassic                     0.3.5
nbclient                      0.5.13
nbconvert                     6.4.4
nbformat                      5.3.0
nest-asyncio                  1.5.5
networkx                      2.7.1
nltk                          3.7
nose                          1.3.7
notebook                      6.4.8
numba                         0.55.1
numexpr                       2.8.1
numpy                         1.21.5
numpydoc                      1.2
nuscenes-devkit               1.1.9
olefile                       0.46
opencv-python                 4.6.0.66
openpyxl                      3.0.9
opt-einsum                    3.3.0
packaging                     21.3
paddle-bfloat                 0.1.2
paddle3d                      0.5.0                /home/tudatong/zyx/Paddle3D
paddledet                     2.4.0
paddlepaddle-gpu              2.3.0
paddleseg                     2.6.0
pandas                        1.4.2
pandocfilters                 1.5.0
panel                         0.13.0
param                         1.12.0
parsel                        1.6.0
parso                         0.8.3
partd                         1.2.0
pathspec                      0.7.0
patsy                         0.5.2
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.2
pip                           21.2.4
pkginfo                       1.8.2
plotly                        5.6.0
pluggy                        1.0.0
poyo                          0.5.0
prettytable                   3.3.0
prometheus-client             0.13.1
prompt-toolkit                3.0.20
Protego                       0.1.16
protobuf                      3.19.1
psutil                        5.8.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycocotools                   2.0.4
pycodestyle                   2.7.0
pycosat                       0.6.3
pycparser                     2.21
pycryptodome                  3.15.0
pyct                          0.4.6
pycurl                        7.44.1
PyDispatcher                  2.0.5
pydocstyle                    6.1.1
pyerfa                        2.0.0
pyflakes                      2.3.1
Pygments                      2.11.2
PyHamcrest                    2.0.2
PyJWT                         2.1.0
pylint                        2.9.6
pyls-spyder                   0.4.0
pyodbc                        4.0.32
pyOpenSSL                     21.0.0
pyparsing                     3.0.4
pyquaternion                  0.9.9
pyrsistent                    0.18.0
PySocks                       1.7.1
pytest                        7.1.1
python-dateutil               2.8.2
python-lsp-black              1.0.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.2.4
python-slugify                5.0.2
python-snappy                 0.6.0
pytz                          2021.3
pyviz-comms                   2.0.2
PyWavelets                    1.3.0
pyxdg                         0.27
PyYAML                        6.0
pyzmq                         22.3.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.3.0
QtPy                          2.0.1
queuelib                      1.5.0
rarfile                       4.0
regex                         2022.3.15
requests                      2.27.1
requests-file                 1.5.1
rope                          0.22.0
rsa                           4.7.2
Rtree                         0.9.7
ruamel-yaml-conda             0.15.100
s3transfer                    0.5.0
scikit-image                  0.19.2
scikit-learn                  1.0.2
scikit-learn-intelex          2021.20220215.212715
scipy                         1.7.3
Scrapy                        2.6.1
seaborn                       0.11.2
SecretStorage                 3.3.1
Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    61.2.0
Shapely                       1.8.4
sip                           4.19.13
six                           1.16.0
sklearn                       0.0
smart-open                    5.1.0
sniffio                       1.2.0
snowballstemmer               2.2.0
sortedcollections             2.1.0
sortedcontainers              2.4.0
soupsieve                     2.3.1
Sphinx                        4.4.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.1.5
spyder-kernels                2.1.3
SQLAlchemy                    1.4.32
stack-data                    0.2.0
statsmodels                   0.13.2
sympy                         1.10.1
tables                        3.6.1
tabulate                      0.8.9
TBB                           0.2
tblib                         1.7.0
tenacity                      8.0.1
termcolor                     1.1.0
terminado                     0.13.1
terminaltables                3.1.10
testpath                      0.5.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tifffile                      2021.7.2
tinycss                       0.4
tldextract                    3.2.0
toml                          0.10.2
tomli                         1.2.2
toolz                         0.11.2
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.1.1
Twisted                       22.2.0
typed-ast                     1.4.3
typeguard                     2.13.3
typing_extensions             4.1.1
ujson                         5.1.0
Unidecode                     1.2.0
urllib3                       1.26.9
visualdl                      2.4.0
w3lib                         1.21.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.58.0
Werkzeug                      2.0.3
wheel                         0.37.1
widgetsnbextension            3.5.2
wrapt                         1.12.1
wurlitzer                     3.0.2
xarray                        0.20.1
xlrd                          2.0.1
XlsxWriter                    3.0.3
xmltodict                     0.13.0
yapf                          0.31.0
yarl                          1.6.3
zict                          2.0.0
zipp                          3.7.0
zope.interface                5.4.0

**Comment by FlyingQianMM** [comment]
> paddlepaddle-gpu 2.3.0
升级下paddlepaddle-gpu试试

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
