### ISSUE TITLE
可以增加RandLA-Net点云语义分割网络吗

### ISSUE THREAD

**Issue by zcy1065670505** [PaddlePaddle/Paddle3D#58]

**Comment by nepeplwu** [comment]
@zcy1065670505 感谢反馈，想请问下您的使用场景是什么样的？是否可以用[ssg v3](https://github.com/PaddlePaddle/Paddle3D/tree/develop/docs/models/squeezesegv3)？

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
