### ISSUE TITLE
win10系统  训练时报ERROR - voxelize builded fail!

### ISSUE THREAD

**Issue by xufangling** [PaddlePaddle/Paddle3D#62]
跑源代码：python tools/train.py --config configs/centerpoint/centerpoint_pillars_016voxel_minikitti.yml --save_dir ./output_kitti --num_workers 3 --save_interval 5 --model h
ttps://bj.bcebos.com/paddle3d/models/centerpoint//centerpoint_pillars_016voxel_kitti/model.pdparams

error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
2022-08-31 10:00:23,389 -    ERROR - voxelize builded fail!

**Comment by FlyingQianMM** [comment]
问题已收到，我们先看下，解决后再同步修复办法~

**Comment by FlyingQianMM** [comment]
这个报错是链接错误，看下前面是链哪些文件时出这个错误。如果是文件缺失，需要对应安装。

我们在CUDA11.2/cuDNN8.1/VS2019/Python37/PaddlePaddle_gpu 2.3.1下边可正常运行。

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
