### ISSUE TITLE
ssgv3对是否支持.cls的标签文件和.pcd的点云文件

### ISSUE THREAD

**Issue by YingYan0** [PaddlePaddle/Paddle3D#66]

**Comment by will-jl944** [comment]
需要参照 https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/transforms/reader.py#L189 自定义一个读取你所需格式文件的Transform，其中需包含：
1. 读取所需格式的标签以及点云
2. 依据你的激光雷达参数（见`__init__`中的成员变量），将标签和点云投影至range view

**Comment by YingYan0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue

**Comment by YingYan0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
