### ISSUE TITLE
请问 FCOS3D 预计什么时间可以集成进来？

### ISSUE THREAD

**Issue by nullnonenilNULL** [PaddlePaddle/Paddle3D#67]
如题。

**Comment by nepeplwu** [comment]
@nullnonenilNULL 目前Paddle3D的[论文复现赛](https://github.com/PaddlePaddle/Paddle/issues/44501)中有同学正在复现FCOS3D的模型，目前还在复现中，具体完成时间还无法评估，请耐心等待~

**Comment by nullnonenilNULL** [comment]
好的，感谢回复；
