### ISSUE TITLE
对于训练出来的PointPillars、CenterPoint模型，模型推理是否有可视化代码？

### ISSUE THREAD

**Issue by Aruen24** [PaddlePaddle/Paddle3D#68]

**Comment by FlyingQianMM** [comment]
借助图像来可视化点云推理结果的示例代码可以参考[AIstudio上的教程](https://aistudio.baidu.com/aistudio/projectdetail/4455993) 中代码：show_lidar_pred_on_image.py

需要可视化界面的纯点云可视化示例代码，这周我们整理好之后给出。

**Comment by Aruen24** [comment]
> 

@FlyingQianMM 
期待点云可视化代码

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
