### ISSUE TITLE
Smoke C++ inference 报错

### ISSUE THREAD

**Issue by bulalaqo** [PaddlePaddle/Paddle3D#79]
/Paddle3D/deploy/smoke/cpp$ ./build/infer --model_file ../../../exported_model/inference.pdmodel --params_file ../../../exported_model/inference.pdiparams --image ../../../datasets/KITTI/training/image_2/000004.png
./build/infer: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

本地查找到了libiomp5.so如下
/Paddle3D/deploy/smoke/cpp/lib/paddle_inference/third_party/install/mklml/lib/libiomp5.so

**Comment by jiangjiajun** [comment]
通过将这个路径添加到LD_LIBRARY_PATH来解决

如
`export LD_LIBRARY_PATH=/Paddle3D/deploy/smoke/cpp/lib/paddle_inference/third_party/install/mklml/lib:${LD_LIBRARY_PATH}`

如若还存在其它类似的问题，都可采用这个方式来解决

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
