### ISSUE TITLE
caddn paddle模型

### ISSUE THREAD

**Issue by dahwang22** [PaddlePaddle/Paddle3D#80]
你好，请问方便分享caddn的模型文件么？

**Comment by dahwang22** [comment]
已经找到，谢谢

**Comment by dahwang22** [comment]
找到的预训练模型，[转换出错](https://github.com/PaddlePaddle/Paddle3D/issues/82#issuecomment-1246134531)

**Comment by wangna11BD** [comment]
我这边试了一下是可以正常导出的～
caddn模型需要编译paddle3d/ops下的自定义算子，可以检查一下看看是否编译。[https://bj.bcebos.com/paddle3d/pretrained/deeplabv3_resnet101.pdparams 只有一部分的模型参数，是用来初始化的，模型参数可以换成这个试试 https://paddle3d.bj.bcebos.com/caddn/model/paddle_caddn.pdparams
如果还是报错的话，可以发一下你的环境～

**Comment by nepeplwu** [comment]
该issue较长时间无反馈，先关闭，如有问题请重新打开或者建立新的issue
