### ISSUE TITLE
请问smoke中的一些配置如何针对自己的数据集进行配置？

### ISSUE THREAD

**Issue by weihongwei-zg** [PaddlePaddle/Paddle3D#86]
问题1：默认尺寸是1283，384。但我的图像分辨率率是1920，1088。我期间尝试了多个尺寸效果都极差，要么loss不收敛，要么评估和预测可视化效果极差。例如我尝试的尺度有：原图分辨率（也就是1920，1088，但将batch减小到了2，其他都是4）、安装原图等比例缩小后的[1152, 640]尺度等。请问如何解决？smoke代码里面是不是写死了一些参数导致这么差？
问题2：我针对我的数据集去重新求了位移偏移量和h、l、w的缩放系数（yaml配置文件中），但使用上去后效果也极差。我的重新计算均值代码如下：
`
import glob
import numpy as np
import os
dict_list = {}
total_car = np.array([0,0,0])
total_cyclist = np.array([0,0,0])
total_pedestrian = np.array([0,0,0])
total_big_vehicle = np.array([0,0,0])

z_list = []

for ids, txt_path in enumerate(glob.glob("/home/aistudio/Paddle3D/datasets/KITTI/training/label_2/*")):
    with open(txt_path) as fb:
        label = fb.readlines()
    
    for i in label:
        i = i.split(" ")
        
        name = i[0]
        h = float(i[8])
        w = float(i[9])
        l = float(i[10])
        z = float(i[13])
        if h ==0 and w ==0 and l==0:
            continue
        
        if name == "car":
            z_list.append(z)
            total_car[0] += l
            total_car[1] += h
            total_car[2] += w
        elif name == "cyclist":
            z_list.append(z)
            total_cyclist[0] += l
            total_cyclist[1] += h
            total_cyclist[2] += w
        elif name == "pedestrian":
            z_list.append(z)
            total_pedestrian[0] += l
            total_pedestrian[1] += h
            total_pedestrian[2] += w
        elif name == "van":
            z_list.append(z)
            total_car[0] += l
            total_car[1] += h
            total_car[2] += w
        elif name == "bus":
            z_list.append(z)
            total_big_vehicle[0] += l
            total_big_vehicle[1] += h
            total_big_vehicle[2] += w
        elif name == "truck":
            z_list.append(z)
            total_big_vehicle[0] += l
            total_big_vehicle[1] += h
            total_big_vehicle[2] += w
        if name in dict_list:
            dict_list[str(name)] += 1
        else:
            dict_list[str(name)] = 0
z_list = np.array(z_list)
print(dict_list)
print("--------------------------------------------------")

print(total_car/(dict_list["car"]+dict_list["van"]),total_cyclist/(dict_list["cyclist"]),
    total_pedestrian/(dict_list["pedestrian"]) ,total_big_vehicle/(dict_list["bus"] + dict_list["truck"]))

print("--------------------------------------------------")
mean_z = np.mean(z_list)
print(mean_z)
var_z = np.var(z_list)#方差

print(np.sqrt(var_z))
`

输出如下：

{'cyclist': 83239, 'van': 39896, 'car': 510700, 'trafficcone': 792519, 'unknown_unmovable': 110140, 'truck': 13862, 'tricyclist': 9770, 'motorcyclist': 119235, 'pedestrian': 122094, 'bus': 15746, 'barrow': 583, 'unknowns_movable': 36}
--------------------------------------------------
[3.94803994 0.87672994 1.0609594 ] [0.96018693 0.92360552 0.00324367] [0.00460301 0.99882877 0.00141694] [8.39556877 2.32430424 1.94535261]

--------------------------------------------------
73.73292637346276
37.19668340710629

**Comment by nepeplwu** [comment]
@wobushihuair 

问题1，目前涉及到图像尺寸的地方没有在代码中写死，只需要修改配置文件中的 `input_size` 即可，关于loss不收敛和效果差，可能的原因有：
1. 模型训练的总bs太小，smoke在kitti上训练时的总bs为 4卡 * 8 = 32bs，如果修改尺寸后总bs太小的话，效果可能不会太好
2. 修改bs后，学习率需要相应的减少，一般是按比例减少，另外实际的学习率也需要根据数据集重新调整一组比较好的参数
3. 修改了训练时所用的尺寸，在使用评估或者推理脚本时，需要记得将尺寸也修改为一致的尺寸
4. 在验证集上的效果太差，可以看看在训练集上的效果，如果训练集效果好，验证集效果差，说明过拟合了

问题2：
1. 从指标上来看，单车和行人的 长宽高 都非常不合理，感觉大概率是统计错误
2. 脚本上初步看，主要的问题在于下面的代码中，numpy默认的类型为 `int` ，应该都是 `float`
  ```python
  total_car = np.array([0,0,0])
  total_cyclist = np.array([0,0,0])
  total_pedestrian = np.array([0,0,0])
  total_big_vehicle = np.array([0,0,0])
  ```

**Comment by weihongwei-zg** [comment]
感谢，问题2中确实是默认int，重新计算后的hwl收敛比默认的好，但z值的均值和尺度方差还是重新计算后效果差（做了对比实验，控制了单一变量）。

**Comment by weihongwei-zg** [comment]
问题1中的尺寸问题，我对照实验中bs和学习率都是一样，分别用了等比例缩放的[1152, 640] 和默认的【1283，384】，只有这一个单一变量是不一样的，等比例缩放的效果极差（在训练集上也是），评估中的各种尺寸都是有对应的，并且可视化看了预测结果。bs我是4，如果是32/4=8，学习率就从0.000125变成了0.000015了，会不会太小了，我再试试稍微减小一点的

**Comment by nepeplwu** [comment]
> 分别用了等比例缩放的[1152, 640] 和默认的【1283，384】，只有这一个单一变量是不一样的，等比例缩放的效果极差（在训练集上也是）

用 `[1920，1088]` 和 `[1283，384]` 两者的效果如何呢

**Comment by weihongwei-zg** [comment]
用[1920，1088]时候的bs=2，效果也没有[1283，384]时候好。正常类看等比例缩放应该要比默认好才对

**Comment by nepeplwu** [comment]
等比例缩放的时候，对内参K的 `f_x` / `f_y` / `c_x` / `c_y` 是否有做等比例处理

**Comment by weihongwei-zg** [comment]
我没有去改内参，内参处理都是默认的，我的缩放也只是改了配置文件。

**Comment by nepeplwu** [comment]
试试等比例的处理下内参

**Comment by weihongwei-zg** [comment]
enen

**Comment by weihongwei-zg** [comment]
缩放完后的内参，都是在减小分辨率后的像素平面计算的，例如1284像素平面。我最后的预测结果需要映射回原图，但是我发现我直接把预测结果的2d乘以缩放系数变回去，eval的评估结果ap准确率只有直接在1284像素平面计算出来的准确率的一半不到，请问什么原因？理论上应该一样才对？很奇怪bug

**Comment by weihongwei-zg** [comment]
实验1：准确率高（0.68）的没问题，处理label时候把2d坐标除以缩放系数（radio），在1284像素坐标系下评估
对照实验2：label坐标不动，把预测结果乘以缩放系数（radio），在原图像素坐标系下评估。
实验2的准确率只有0.31

**Comment by weihongwei-zg** [comment]
呜呜呜呜，还请大佬帮忙看看，回复一下

**Comment by weihongwei-zg** [comment]
@nepeplwu

**Comment by weihongwei-zg** [comment]
好像smoke中不需要缩放内参，他会自动适配吧？？

**Comment by NyquistBodeTu** [comment]
> 

我看论文说，smoke模型的深度估计就是和单目相机内参有很大关系。我感觉用自己的相机拍照测试，需要将相机的内参和数据集相机的内参做一个映射
