### ISSUE TITLE
请问一下配置文件中的depth_ref和dim_ref的具体含义是什么呢，请问是标签中的z和lhw吗。还有想请问一下如何根据自己的数据调整相机内参的配置，内参在哪个文件里可以修改呢

### ISSUE THREAD

**Issue by stevenk12** [PaddlePaddle/Paddle3D#93]

**Comment by nepeplwu** [comment]
@stevenk12 

> 请问一下配置文件中的depth_ref和dim_ref的具体含义是什么呢，请问是标签中的z和lhw吗。

是的

> 还有想请问一下如何根据自己的数据调整相机内参的配置，内参在哪个文件里可以修改呢

目前SMOKE只适配了KITTI数据集，KITTI数据集中内参是写在数据集的文件中的，目录为 `KITTI/training/calib/`，每个txt文件给出了对应样本的内参外参，目前使用的主要是P2

**Comment by stevenk12** [comment]
好的 谢谢！
