### ISSUE TITLE
请问作者，CaDDN不是单目检测算法，不需要点云吗。为什么您仓库下的CaDDN的实例操作，数据集有点云呢。能否不需要点云

### ISSUE THREAD

**Issue by stevenk12** [PaddlePaddle/Paddle3D#96]

**Comment by wangna11BD** [comment]
CaDDN是单目检测算法， 不需要点云数据。这里的点云数据在生成caddn_kitti_infos时有段代码用到了，您可以选择一下两种方法绕过点云数据的调用：
1. 直接从这里[kitti_infos.zip](https://github.com/PaddlePaddle/Paddle3D/files/9356172/kitti_infos.zip)下载.pkl文件，不用自己生成
2. 注释掉这个if分支 https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/datasets/kitti/kitti_depth_det.py#L274

**Comment by stevenk12** [comment]
谢谢作者，明白了
